/**
 * Talon.One API
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TalononeApi) {
      root.TalononeApi = {};
    }
    root.TalononeApi.ApplicationAPIKey = factory(root.TalononeApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ApplicationAPIKey model module.
   * @module model/ApplicationAPIKey
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ApplicationAPIKey</code>.
   * @alias module:model/ApplicationAPIKey
   * @class
   * @param ID {Number} ID of the API Key
   * @param accountID {Number} ID of account the key is used for
   * @param applicationID {Number} ID of application the key is used for
   * @param created {Date} The date the API key was created
   * @param expires {Date} The date the API key expired
   */
  var exports = function(ID, accountID, applicationID, created, expires) {
    var _this = this;

    _this['ID'] = ID;
    _this['AccountID'] = accountID;
    _this['ApplicationID'] = applicationID;
    _this['Created'] = created;
    _this['Expires'] = expires;
  };

  /**
   * Constructs a <code>ApplicationAPIKey</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApplicationAPIKey} obj Optional instance to populate.
   * @return {module:model/ApplicationAPIKey} The populated <code>ApplicationAPIKey</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ID')) {
        obj['ID'] = ApiClient.convertToType(data['ID'], 'Number');
      }
      if (data.hasOwnProperty('AccountID')) {
        obj['AccountID'] = ApiClient.convertToType(data['AccountID'], 'Number');
      }
      if (data.hasOwnProperty('ApplicationID')) {
        obj['ApplicationID'] = ApiClient.convertToType(data['ApplicationID'], 'Number');
      }
      if (data.hasOwnProperty('Created')) {
        obj['Created'] = ApiClient.convertToType(data['Created'], 'Date');
      }
      if (data.hasOwnProperty('Expires')) {
        obj['Expires'] = ApiClient.convertToType(data['Expires'], 'Date');
      }
    }
    return obj;
  }

  /**
   * ID of the API Key
   * @member {Number} ID
   */
  exports.prototype['ID'] = undefined;
  /**
   * ID of account the key is used for
   * @member {Number} AccountID
   */
  exports.prototype['AccountID'] = undefined;
  /**
   * ID of application the key is used for
   * @member {Number} ApplicationID
   */
  exports.prototype['ApplicationID'] = undefined;
  /**
   * The date the API key was created
   * @member {Date} Created
   */
  exports.prototype['Created'] = undefined;
  /**
   * The date the API key expired
   * @member {Date} Expires
   */
  exports.prototype['Expires'] = undefined;



  return exports;
}));


