/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AsyncCouponsData model module.
 * @module model/AsyncCouponsData
 * @version 25.16.0
 */
class AsyncCouponsData {
    /**
     * Constructs a new <code>AsyncCouponsData</code>.
     * @alias module:model/AsyncCouponsData
     * @param batchID {String} The ID of the batch to which the coupon belongs.  **Note:** The Batch ID is generated when coupons are created. 
     * @param typeOfChange {String} 
     * @param operation {String} 
     * @param employeeName {String} 
     * @param notificationType {String} The type of the notification
     */
    constructor(batchID, typeOfChange, operation, employeeName, notificationType) { 
        
        AsyncCouponsData.initialize(this, batchID, typeOfChange, operation, employeeName, notificationType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, batchID, typeOfChange, operation, employeeName, notificationType) { 
        obj['BatchID'] = batchID;
        obj['TypeOfChange'] = typeOfChange;
        obj['Operation'] = operation;
        obj['EmployeeName'] = employeeName;
        obj['NotificationType'] = notificationType;
    }

    /**
     * Constructs a <code>AsyncCouponsData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AsyncCouponsData} obj Optional instance to populate.
     * @return {module:model/AsyncCouponsData} The populated <code>AsyncCouponsData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AsyncCouponsData();

            if (data.hasOwnProperty('BatchID')) {
                obj['BatchID'] = ApiClient.convertToType(data['BatchID'], 'String');
            }
            if (data.hasOwnProperty('TypeOfChange')) {
                obj['TypeOfChange'] = ApiClient.convertToType(data['TypeOfChange'], 'String');
            }
            if (data.hasOwnProperty('Operation')) {
                obj['Operation'] = ApiClient.convertToType(data['Operation'], 'String');
            }
            if (data.hasOwnProperty('EmployeeName')) {
                obj['EmployeeName'] = ApiClient.convertToType(data['EmployeeName'], 'String');
            }
            if (data.hasOwnProperty('NotificationType')) {
                obj['NotificationType'] = ApiClient.convertToType(data['NotificationType'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The ID of the batch to which the coupon belongs.  **Note:** The Batch ID is generated when coupons are created. 
 * @member {String} BatchID
 */
AsyncCouponsData.prototype['BatchID'] = undefined;

/**
 * 
 * @member {String} TypeOfChange
 */
AsyncCouponsData.prototype['TypeOfChange'] = undefined;

/**
 * 
 * @member {String} Operation
 */
AsyncCouponsData.prototype['Operation'] = undefined;

/**
 * 
 * @member {String} EmployeeName
 */
AsyncCouponsData.prototype['EmployeeName'] = undefined;

/**
 * The type of the notification
 * @member {String} NotificationType
 */
AsyncCouponsData.prototype['NotificationType'] = undefined;






export default AsyncCouponsData;

