/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PatchManyItemsCatalogAction from './PatchManyItemsCatalogAction';

/**
 * The CatalogActionPatchMany model module.
 * @module model/CatalogActionPatchMany
 * @version 25.18.0
 */
class CatalogActionPatchMany {
    /**
     * Constructs a new <code>CatalogActionPatchMany</code>.
     * Updates the items of the catalog that match the given filters.
     * @alias module:model/CatalogActionPatchMany
     * @param type {module:model/CatalogActionPatchMany.TypeEnum} A catalog sync action discriminator of type `PATCH_MANY`.
     * @param payload {module:model/PatchManyItemsCatalogAction} 
     */
    constructor(type, payload) { 
        
        CatalogActionPatchMany.initialize(this, type, payload);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, payload) { 
        obj['type'] = type;
        obj['payload'] = payload;
    }

    /**
     * Constructs a <code>CatalogActionPatchMany</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CatalogActionPatchMany} obj Optional instance to populate.
     * @return {module:model/CatalogActionPatchMany} The populated <code>CatalogActionPatchMany</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CatalogActionPatchMany();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = PatchManyItemsCatalogAction.constructFromObject(data['payload']);
            }
        }
        return obj;
    }


}

/**
 * A catalog sync action discriminator of type `PATCH_MANY`.
 * @member {module:model/CatalogActionPatchMany.TypeEnum} type
 */
CatalogActionPatchMany.prototype['type'] = undefined;

/**
 * @member {module:model/PatchManyItemsCatalogAction} payload
 */
CatalogActionPatchMany.prototype['payload'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
CatalogActionPatchMany['TypeEnum'] = {

    /**
     * value: "PATCH_MANY"
     * @const
     */
    "PATCH_MANY": "PATCH_MANY"
};



export default CatalogActionPatchMany;

