/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CheckTierBlockTier model module.
 * @module model/CheckTierBlockTier
 * @version 25.18.0
 */
class CheckTierBlockTier {
    /**
     * Constructs a new <code>CheckTierBlockTier</code>.
     * @alias module:model/CheckTierBlockTier
     * @param id {Number} The ID of the tier.
     * @param name {String} The display name of the tier.
     * @param minPoints {Number} The minimum amount of points required to enter the tier.
     */
    constructor(id, name, minPoints) { 
        
        CheckTierBlockTier.initialize(this, id, name, minPoints);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, minPoints) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['minPoints'] = minPoints;
    }

    /**
     * Constructs a <code>CheckTierBlockTier</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CheckTierBlockTier} obj Optional instance to populate.
     * @return {module:model/CheckTierBlockTier} The populated <code>CheckTierBlockTier</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckTierBlockTier();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('minPoints')) {
                obj['minPoints'] = ApiClient.convertToType(data['minPoints'], 'Number');
            }
            if (data.hasOwnProperty('upperLimit')) {
                obj['upperLimit'] = ApiClient.convertToType(data['upperLimit'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The ID of the tier.
 * @member {Number} id
 */
CheckTierBlockTier.prototype['id'] = undefined;

/**
 * The display name of the tier.
 * @member {String} name
 */
CheckTierBlockTier.prototype['name'] = undefined;

/**
 * The minimum amount of points required to enter the tier.
 * @member {Number} minPoints
 */
CheckTierBlockTier.prototype['minPoints'] = undefined;

/**
 * @member {Number} upperLimit
 */
CheckTierBlockTier.prototype['upperLimit'] = undefined;






export default CheckTierBlockTier;

