/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateCouponBlock model module.
 * @module model/CreateCouponBlock
 * @version 25.18.0
 */
class CreateCouponBlock {
    /**
     * Constructs a new <code>CreateCouponBlock</code>.
     * A block that creates a coupon code.
     * @alias module:model/CreateCouponBlock
     * @param type {String} Identifies the block variant and determines which additional properties are present in it.
     * @param campaignId {Object} The ID of the campaign in which the coupon code is created.
     * @param recipientId {String} The integration ID of the customer that is allowed to redeem this coupon.
     * @param storeInSession {Boolean} When `true`, the coupon is stored in the session.
     */
    constructor(type, campaignId, recipientId, storeInSession) { 
        
        CreateCouponBlock.initialize(this, type, campaignId, recipientId, storeInSession);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, campaignId, recipientId, storeInSession) { 
        obj['type'] = type;
        obj['campaignId'] = campaignId;
        obj['recipientId'] = recipientId;
        obj['storeInSession'] = storeInSession;
    }

    /**
     * Constructs a <code>CreateCouponBlock</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateCouponBlock} obj Optional instance to populate.
     * @return {module:model/CreateCouponBlock} The populated <code>CreateCouponBlock</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateCouponBlock();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
            if (data.hasOwnProperty('campaignId')) {
                obj['campaignId'] = ApiClient.convertToType(data['campaignId'], Object);
            }
            if (data.hasOwnProperty('recipientId')) {
                obj['recipientId'] = ApiClient.convertToType(data['recipientId'], 'String');
            }
            if (data.hasOwnProperty('storeInSession')) {
                obj['storeInSession'] = ApiClient.convertToType(data['storeInSession'], 'Boolean');
            }
            if (data.hasOwnProperty('usageLimit')) {
                obj['usageLimit'] = ApiClient.convertToType(data['usageLimit'], Object);
            }
            if (data.hasOwnProperty('discountLimit')) {
                obj['discountLimit'] = ApiClient.convertToType(data['discountLimit'], Object);
            }
            if (data.hasOwnProperty('startDate')) {
                obj['startDate'] = ApiClient.convertToType(data['startDate'], Object);
            }
            if (data.hasOwnProperty('expiryDate')) {
                obj['expiryDate'] = ApiClient.convertToType(data['expiryDate'], Object);
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], Object);
            }
            if (data.hasOwnProperty('validCharacters')) {
                obj['validCharacters'] = ApiClient.convertToType(data['validCharacters'], 'String');
            }
            if (data.hasOwnProperty('pattern')) {
                obj['pattern'] = ApiClient.convertToType(data['pattern'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Unique identifier for this block.
 * @member {String} id
 */
CreateCouponBlock.prototype['id'] = undefined;

/**
 * Identifies the block variant and determines which additional properties are present in it.
 * @member {String} type
 */
CreateCouponBlock.prototype['type'] = undefined;

/**
 * Semantic labels attached to this block.
 * @member {Array.<String>} tags
 */
CreateCouponBlock.prototype['tags'] = undefined;

/**
 * The ID of the campaign in which the coupon code is created.
 * @member {Object} campaignId
 */
CreateCouponBlock.prototype['campaignId'] = undefined;

/**
 * The integration ID of the customer that is allowed to redeem this coupon.
 * @member {String} recipientId
 */
CreateCouponBlock.prototype['recipientId'] = undefined;

/**
 * When `true`, the coupon is stored in the session.
 * @member {Boolean} storeInSession
 */
CreateCouponBlock.prototype['storeInSession'] = undefined;

/**
 * The number of times the coupon code can be redeemed. `0` means unlimited redemptions, but any campaign usage limits still apply. Either a numeric scalar or a `{{expression}}` string that resolves to a number at evaluation time. 
 * @member {Object} usageLimit
 */
CreateCouponBlock.prototype['usageLimit'] = undefined;

/**
 * The total discount value that the code can give. Typically used to represent a gift card value. Either a numeric scalar or a `{{expression}}` string that resolves to a number at evaluation time. 
 * @member {Object} discountLimit
 */
CreateCouponBlock.prototype['discountLimit'] = undefined;

/**
 * Timestamp at which point the coupon becomes valid.
 * @member {Object} startDate
 */
CreateCouponBlock.prototype['startDate'] = undefined;

/**
 * Expiration date of the coupon. Coupon never expires if this is omitted.
 * @member {Object} expiryDate
 */
CreateCouponBlock.prototype['expiryDate'] = undefined;

/**
 * Custom attributes associated with this coupon code.
 * @member {Object} attributes
 */
CreateCouponBlock.prototype['attributes'] = undefined;

/**
 * Characters used to generate the random parts of a code.
 * @member {String} validCharacters
 */
CreateCouponBlock.prototype['validCharacters'] = undefined;

/**
 * The pattern used to generate codes, such as coupon codes, referral codes, and loyalty cards. The character `#` is a placeholder and is replaced by a random character from the `validCharacters` set. 
 * @member {String} pattern
 */
CreateCouponBlock.prototype['pattern'] = undefined;






export default CreateCouponBlock;

