/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://mycompany.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeductLoyaltyPoints model module.
 * @module model/DeductLoyaltyPoints
 * @version 5.0.0
 */
class DeductLoyaltyPoints {
    /**
     * Constructs a new <code>DeductLoyaltyPoints</code>.
     * Points to deduct.
     * @alias module:model/DeductLoyaltyPoints
     * @param points {Number} Amount of loyalty points.
     */
    constructor(points) { 
        
        DeductLoyaltyPoints.initialize(this, points);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, points) { 
        obj['points'] = points;
    }

    /**
     * Constructs a <code>DeductLoyaltyPoints</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeductLoyaltyPoints} obj Optional instance to populate.
     * @return {module:model/DeductLoyaltyPoints} The populated <code>DeductLoyaltyPoints</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeductLoyaltyPoints();

            if (data.hasOwnProperty('points')) {
                obj['points'] = ApiClient.convertToType(data['points'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('subledgerId')) {
                obj['subledgerId'] = ApiClient.convertToType(data['subledgerId'], 'String');
            }
            if (data.hasOwnProperty('applicationId')) {
                obj['applicationId'] = ApiClient.convertToType(data['applicationId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Amount of loyalty points.
 * @member {Number} points
 */
DeductLoyaltyPoints.prototype['points'] = undefined;

/**
 * Name / reason for the point deduction.
 * @member {String} name
 */
DeductLoyaltyPoints.prototype['name'] = undefined;

/**
 * ID of the subledger the points are deducted from.
 * @member {String} subledgerId
 */
DeductLoyaltyPoints.prototype['subledgerId'] = undefined;

/**
 * ID of the Application that is connected to the loyalty program.
 * @member {Number} applicationId
 */
DeductLoyaltyPoints.prototype['applicationId'] = undefined;






export default DeductLoyaltyPoints;

