/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExperimentSegmentInsightMetric from './ExperimentSegmentInsightMetric';

/**
 * The ExperimentSegmentInsights model module.
 * @module model/ExperimentSegmentInsights
 * @version 25.17.0
 */
class ExperimentSegmentInsights {
    /**
     * Constructs a new <code>ExperimentSegmentInsights</code>.
     * @alias module:model/ExperimentSegmentInsights
     * @param metrics {Array.<module:model/ExperimentSegmentInsightMetric>} Segment insights grouped by metric. This array always contains exactly three metric objects. Each metric includes a segments array, which is empty if no significant results were found. The metrics array itself is empty if the `reason` property is populated. 
     * @param totalSegmentsTested {Number} Total number of segment-metric combinations that were tested for statistical significance. 
     * @param dimensionsTested {Number} Number of segmentation dimensions that had sufficient data variance to test. Dimensions where all sessions fall into a single bucket are excluded. 
     * @param reason {String} Empty string when segment insights are available. Contains a reason code when insights could not be computed (e.g., \"insufficient_data\" when the experiment has fewer than 100 sessions per variant). 
     */
    constructor(metrics, totalSegmentsTested, dimensionsTested, reason) { 
        
        ExperimentSegmentInsights.initialize(this, metrics, totalSegmentsTested, dimensionsTested, reason);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, metrics, totalSegmentsTested, dimensionsTested, reason) { 
        obj['metrics'] = metrics;
        obj['totalSegmentsTested'] = totalSegmentsTested;
        obj['dimensionsTested'] = dimensionsTested;
        obj['reason'] = reason;
    }

    /**
     * Constructs a <code>ExperimentSegmentInsights</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExperimentSegmentInsights} obj Optional instance to populate.
     * @return {module:model/ExperimentSegmentInsights} The populated <code>ExperimentSegmentInsights</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExperimentSegmentInsights();

            if (data.hasOwnProperty('metrics')) {
                obj['metrics'] = ApiClient.convertToType(data['metrics'], [ExperimentSegmentInsightMetric]);
            }
            if (data.hasOwnProperty('totalSegmentsTested')) {
                obj['totalSegmentsTested'] = ApiClient.convertToType(data['totalSegmentsTested'], 'Number');
            }
            if (data.hasOwnProperty('dimensionsTested')) {
                obj['dimensionsTested'] = ApiClient.convertToType(data['dimensionsTested'], 'Number');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Segment insights grouped by metric. This array always contains exactly three metric objects. Each metric includes a segments array, which is empty if no significant results were found. The metrics array itself is empty if the `reason` property is populated. 
 * @member {Array.<module:model/ExperimentSegmentInsightMetric>} metrics
 */
ExperimentSegmentInsights.prototype['metrics'] = undefined;

/**
 * Total number of segment-metric combinations that were tested for statistical significance. 
 * @member {Number} totalSegmentsTested
 */
ExperimentSegmentInsights.prototype['totalSegmentsTested'] = undefined;

/**
 * Number of segmentation dimensions that had sufficient data variance to test. Dimensions where all sessions fall into a single bucket are excluded. 
 * @member {Number} dimensionsTested
 */
ExperimentSegmentInsights.prototype['dimensionsTested'] = undefined;

/**
 * Empty string when segment insights are available. Contains a reason code when insights could not be computed (e.g., \"insufficient_data\" when the experiment has fewer than 100 sessions per variant). 
 * @member {String} reason
 */
ExperimentSegmentInsights.prototype['reason'] = undefined;






export default ExperimentSegmentInsights;

