/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HiddenConditionsEffects model module.
 * @module model/HiddenConditionsEffects
 * @version 25.15.0
 */
class HiddenConditionsEffects {
    /**
     * Constructs a new <code>HiddenConditionsEffects</code>.
     * Contains information about hidden conditions and effects in the Application.
     * @alias module:model/HiddenConditionsEffects
     */
    constructor() { 
        
        HiddenConditionsEffects.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HiddenConditionsEffects</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HiddenConditionsEffects} obj Optional instance to populate.
     * @return {module:model/HiddenConditionsEffects} The populated <code>HiddenConditionsEffects</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HiddenConditionsEffects();

            if (data.hasOwnProperty('builtInEffects')) {
                obj['builtInEffects'] = ApiClient.convertToType(data['builtInEffects'], ['String']);
            }
            if (data.hasOwnProperty('conditions')) {
                obj['conditions'] = ApiClient.convertToType(data['conditions'], ['String']);
            }
            if (data.hasOwnProperty('customEffects')) {
                obj['customEffects'] = ApiClient.convertToType(data['customEffects'], ['Number']);
            }
            if (data.hasOwnProperty('webhooks')) {
                obj['webhooks'] = ApiClient.convertToType(data['webhooks'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * List of hidden built-in effects.
 * @member {Array.<String>} builtInEffects
 */
HiddenConditionsEffects.prototype['builtInEffects'] = undefined;

/**
 * List of hidden conditions.
 * @member {Array.<String>} conditions
 */
HiddenConditionsEffects.prototype['conditions'] = undefined;

/**
 * List of the IDs of hidden custom effects.
 * @member {Array.<Number>} customEffects
 */
HiddenConditionsEffects.prototype['customEffects'] = undefined;

/**
 * List of the IDs of hidden webhooks.
 * @member {Array.<Number>} webhooks
 */
HiddenConditionsEffects.prototype['webhooks'] = undefined;






export default HiddenConditionsEffects;

