/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IntegrationHubEventPayloadCouponBasedNotificationsLimits model module.
 * @module model/IntegrationHubEventPayloadCouponBasedNotificationsLimits
 * @version 25.17.0
 */
class IntegrationHubEventPayloadCouponBasedNotificationsLimits {
    /**
     * Constructs a new <code>IntegrationHubEventPayloadCouponBasedNotificationsLimits</code>.
     * @alias module:model/IntegrationHubEventPayloadCouponBasedNotificationsLimits
     * @param action {String} 
     * @param limit {Number} 
     * @param entities {Array.<String>} 
     */
    constructor(action, limit, entities) { 
        
        IntegrationHubEventPayloadCouponBasedNotificationsLimits.initialize(this, action, limit, entities);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, action, limit, entities) { 
        obj['Action'] = action;
        obj['Limit'] = limit;
        obj['Entities'] = entities;
    }

    /**
     * Constructs a <code>IntegrationHubEventPayloadCouponBasedNotificationsLimits</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IntegrationHubEventPayloadCouponBasedNotificationsLimits} obj Optional instance to populate.
     * @return {module:model/IntegrationHubEventPayloadCouponBasedNotificationsLimits} The populated <code>IntegrationHubEventPayloadCouponBasedNotificationsLimits</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IntegrationHubEventPayloadCouponBasedNotificationsLimits();

            if (data.hasOwnProperty('Action')) {
                obj['Action'] = ApiClient.convertToType(data['Action'], 'String');
            }
            if (data.hasOwnProperty('Limit')) {
                obj['Limit'] = ApiClient.convertToType(data['Limit'], 'Number');
            }
            if (data.hasOwnProperty('Period')) {
                obj['Period'] = ApiClient.convertToType(data['Period'], 'String');
            }
            if (data.hasOwnProperty('Entities')) {
                obj['Entities'] = ApiClient.convertToType(data['Entities'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} Action
 */
IntegrationHubEventPayloadCouponBasedNotificationsLimits.prototype['Action'] = undefined;

/**
 * @member {Number} Limit
 */
IntegrationHubEventPayloadCouponBasedNotificationsLimits.prototype['Limit'] = undefined;

/**
 * @member {String} Period
 */
IntegrationHubEventPayloadCouponBasedNotificationsLimits.prototype['Period'] = undefined;

/**
 * @member {Array.<String>} Entities
 */
IntegrationHubEventPayloadCouponBasedNotificationsLimits.prototype['Entities'] = undefined;






export default IntegrationHubEventPayloadCouponBasedNotificationsLimits;

