/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class IntegrationHubEventType.
* @enum {}
* @readonly
*/
export default class IntegrationHubEventType {
    
        /**
         * value: "LoyaltyPointsChanged"
         * @const
         */
        "LoyaltyPointsChanged" = "LoyaltyPointsChanged";

    
        /**
         * value: "LoyaltyTierDowngrade"
         * @const
         */
        "LoyaltyTierDowngrade" = "LoyaltyTierDowngrade";

    
        /**
         * value: "LoyaltyTierUpgrade"
         * @const
         */
        "LoyaltyTierUpgrade" = "LoyaltyTierUpgrade";

    
        /**
         * value: "CouponCreated"
         * @const
         */
        "CouponCreated" = "CouponCreated";

    
        /**
         * value: "CouponUpdated"
         * @const
         */
        "CouponUpdated" = "CouponUpdated";

    
        /**
         * value: "CouponDeleted"
         * @const
         */
        "CouponDeleted" = "CouponDeleted";

    

    /**
    * Returns a <code>IntegrationHubEventType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/IntegrationHubEventType} The enum <code>IntegrationHubEventType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

