/**
 * Talon.One API
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoyaltyDashboardPointsBreakdown model module.
 * @module model/LoyaltyDashboardPointsBreakdown
 * @version 4.4.0
 */
class LoyaltyDashboardPointsBreakdown {
    /**
     * Constructs a new <code>LoyaltyDashboardPointsBreakdown</code>.
     * @alias module:model/LoyaltyDashboardPointsBreakdown
     * @param createdManually {Number} 
     * @param createdViaRuleEngine {Number} 
     */
    constructor(createdManually, createdViaRuleEngine) { 
        
        LoyaltyDashboardPointsBreakdown.initialize(this, createdManually, createdViaRuleEngine);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, createdManually, createdViaRuleEngine) { 
        obj['createdManually'] = createdManually;
        obj['createdViaRuleEngine'] = createdViaRuleEngine;
    }

    /**
     * Constructs a <code>LoyaltyDashboardPointsBreakdown</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoyaltyDashboardPointsBreakdown} obj Optional instance to populate.
     * @return {module:model/LoyaltyDashboardPointsBreakdown} The populated <code>LoyaltyDashboardPointsBreakdown</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoyaltyDashboardPointsBreakdown();

            if (data.hasOwnProperty('createdManually')) {
                obj['createdManually'] = ApiClient.convertToType(data['createdManually'], 'Number');
            }
            if (data.hasOwnProperty('createdViaRuleEngine')) {
                obj['createdViaRuleEngine'] = ApiClient.convertToType(data['createdViaRuleEngine'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} createdManually
 */
LoyaltyDashboardPointsBreakdown.prototype['createdManually'] = undefined;

/**
 * @member {Number} createdViaRuleEngine
 */
LoyaltyDashboardPointsBreakdown.prototype['createdViaRuleEngine'] = undefined;






export default LoyaltyDashboardPointsBreakdown;

