/**
 * Talon.One API
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/LoyaltyLedgerEntry'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./LoyaltyLedgerEntry'));
  } else {
    // Browser globals (root is window)
    if (!root.TalonOne) {
      root.TalonOne = {};
    }
    root.TalonOne.LoyaltySubLedger = factory(root.TalonOne.ApiClient, root.TalonOne.LoyaltyLedgerEntry);
  }
}(this, function(ApiClient, LoyaltyLedgerEntry) {
  'use strict';




  /**
   * The LoyaltySubLedger model module.
   * @module model/LoyaltySubLedger
   * @version 3.1.1
   */

  /**
   * Constructs a new <code>LoyaltySubLedger</code>.
   * Ledger of Balance in Loyalty Program for a Customer
   * @alias module:model/LoyaltySubLedger
   * @class
   * @param total {Number} 
   */
  var exports = function(total) {
    var _this = this;

    _this['total'] = total;


  };

  /**
   * Constructs a <code>LoyaltySubLedger</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoyaltySubLedger} obj Optional instance to populate.
   * @return {module:model/LoyaltySubLedger} The populated <code>LoyaltySubLedger</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('total')) {
        obj['total'] = ApiClient.convertToType(data['total'], 'Number');
      }
      if (data.hasOwnProperty('transactions')) {
        obj['transactions'] = ApiClient.convertToType(data['transactions'], [LoyaltyLedgerEntry]);
      }
      if (data.hasOwnProperty('expiringPoints')) {
        obj['expiringPoints'] = ApiClient.convertToType(data['expiringPoints'], [LoyaltyLedgerEntry]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} total
   */
  exports.prototype['total'] = undefined;
  /**
   * Transactions contains a list of all events that have happened such as additions, subtractions and expiries
   * @member {Array.<module:model/LoyaltyLedgerEntry>} transactions
   */
  exports.prototype['transactions'] = undefined;
  /**
   * ExpiringPoints contains a list of all points that will expiry and when
   * @member {Array.<module:model/LoyaltyLedgerEntry>} expiringPoints
   */
  exports.prototype['expiringPoints'] = undefined;



  return exports;
}));


