/**
 * Talon.One API
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LoyaltyLedgerEntry from './LoyaltyLedgerEntry';

/**
 * The LoyaltySubLedger model module.
 * @module model/LoyaltySubLedger
 * @version 10.0.0
 */
class LoyaltySubLedger {
    /**
     * Constructs a new <code>LoyaltySubLedger</code>.
     * Ledger of Balance in Loyalty Program for a Customer
     * @alias module:model/LoyaltySubLedger
     * @param total {Number} ⚠️ Deprecated: Use 'totalActivePoints' property instead. Total amount of currently active and available points in the customer's balance 
     * @param totalActivePoints {Number} Total amount of currently active and available points in the customer's balance
     * @param totalPendingPoints {Number} Total amount of pending points, which are not active yet but will become active in the future
     * @param totalSpentPoints {Number} Total amount of points already spent by this customer
     * @param totalExpiredPoints {Number} Total amount of points, that expired without ever being spent
     */
    constructor(total, totalActivePoints, totalPendingPoints, totalSpentPoints, totalExpiredPoints) { 
        
        LoyaltySubLedger.initialize(this, total, totalActivePoints, totalPendingPoints, totalSpentPoints, totalExpiredPoints);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, total, totalActivePoints, totalPendingPoints, totalSpentPoints, totalExpiredPoints) { 
        obj['total'] = total;
        obj['totalActivePoints'] = totalActivePoints;
        obj['totalPendingPoints'] = totalPendingPoints;
        obj['totalSpentPoints'] = totalSpentPoints;
        obj['totalExpiredPoints'] = totalExpiredPoints;
    }

    /**
     * Constructs a <code>LoyaltySubLedger</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoyaltySubLedger} obj Optional instance to populate.
     * @return {module:model/LoyaltySubLedger} The populated <code>LoyaltySubLedger</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoyaltySubLedger();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('totalActivePoints')) {
                obj['totalActivePoints'] = ApiClient.convertToType(data['totalActivePoints'], 'Number');
            }
            if (data.hasOwnProperty('totalPendingPoints')) {
                obj['totalPendingPoints'] = ApiClient.convertToType(data['totalPendingPoints'], 'Number');
            }
            if (data.hasOwnProperty('totalSpentPoints')) {
                obj['totalSpentPoints'] = ApiClient.convertToType(data['totalSpentPoints'], 'Number');
            }
            if (data.hasOwnProperty('totalExpiredPoints')) {
                obj['totalExpiredPoints'] = ApiClient.convertToType(data['totalExpiredPoints'], 'Number');
            }
            if (data.hasOwnProperty('transactions')) {
                obj['transactions'] = ApiClient.convertToType(data['transactions'], [LoyaltyLedgerEntry]);
            }
            if (data.hasOwnProperty('expiringPoints')) {
                obj['expiringPoints'] = ApiClient.convertToType(data['expiringPoints'], [LoyaltyLedgerEntry]);
            }
            if (data.hasOwnProperty('activePoints')) {
                obj['activePoints'] = ApiClient.convertToType(data['activePoints'], [LoyaltyLedgerEntry]);
            }
            if (data.hasOwnProperty('pendingPoints')) {
                obj['pendingPoints'] = ApiClient.convertToType(data['pendingPoints'], [LoyaltyLedgerEntry]);
            }
            if (data.hasOwnProperty('expiredPoints')) {
                obj['expiredPoints'] = ApiClient.convertToType(data['expiredPoints'], [LoyaltyLedgerEntry]);
            }
        }
        return obj;
    }


}

/**
 * ⚠️ Deprecated: Use 'totalActivePoints' property instead. Total amount of currently active and available points in the customer's balance 
 * @member {Number} total
 */
LoyaltySubLedger.prototype['total'] = undefined;

/**
 * Total amount of currently active and available points in the customer's balance
 * @member {Number} totalActivePoints
 */
LoyaltySubLedger.prototype['totalActivePoints'] = undefined;

/**
 * Total amount of pending points, which are not active yet but will become active in the future
 * @member {Number} totalPendingPoints
 */
LoyaltySubLedger.prototype['totalPendingPoints'] = undefined;

/**
 * Total amount of points already spent by this customer
 * @member {Number} totalSpentPoints
 */
LoyaltySubLedger.prototype['totalSpentPoints'] = undefined;

/**
 * Total amount of points, that expired without ever being spent
 * @member {Number} totalExpiredPoints
 */
LoyaltySubLedger.prototype['totalExpiredPoints'] = undefined;

/**
 * List of all events that have happened such as additions, subtractions and expiries
 * @member {Array.<module:model/LoyaltyLedgerEntry>} transactions
 */
LoyaltySubLedger.prototype['transactions'] = undefined;

/**
 * List of all points that will expire
 * @member {Array.<module:model/LoyaltyLedgerEntry>} expiringPoints
 */
LoyaltySubLedger.prototype['expiringPoints'] = undefined;

/**
 * List of all currently active points
 * @member {Array.<module:model/LoyaltyLedgerEntry>} activePoints
 */
LoyaltySubLedger.prototype['activePoints'] = undefined;

/**
 * List of all points pending activation
 * @member {Array.<module:model/LoyaltyLedgerEntry>} pendingPoints
 */
LoyaltySubLedger.prototype['pendingPoints'] = undefined;

/**
 * List of expired points
 * @member {Array.<module:model/LoyaltyLedgerEntry>} expiredPoints
 */
LoyaltySubLedger.prototype['expiredPoints'] = undefined;






export default LoyaltySubLedger;

