/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MCPOAuthServerMetadata model module.
 * @module model/MCPOAuthServerMetadata
 * @version 25.18.0
 */
class MCPOAuthServerMetadata {
    /**
     * Constructs a new <code>MCPOAuthServerMetadata</code>.
     * @alias module:model/MCPOAuthServerMetadata
     * @param issuer {String} The authorization server's issuer identifier (its base URL).
     * @param authorizationEndpoint {String} URL of the authorization endpoint.
     * @param tokenEndpoint {String} URL of the token endpoint.
     * @param registrationEndpoint {String} URL of the client registration endpoint.
     * @param responseTypesSupported {Array.<String>} List of supported OAuth2 response types.
     * @param grantTypesSupported {Array.<String>} List of supported OAuth2 grant types.
     * @param codeChallengeMethodsSupported {Array.<String>} List of supported PKCE code challenge methods.
     */
    constructor(issuer, authorizationEndpoint, tokenEndpoint, registrationEndpoint, responseTypesSupported, grantTypesSupported, codeChallengeMethodsSupported) { 
        
        MCPOAuthServerMetadata.initialize(this, issuer, authorizationEndpoint, tokenEndpoint, registrationEndpoint, responseTypesSupported, grantTypesSupported, codeChallengeMethodsSupported);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, issuer, authorizationEndpoint, tokenEndpoint, registrationEndpoint, responseTypesSupported, grantTypesSupported, codeChallengeMethodsSupported) { 
        obj['issuer'] = issuer;
        obj['authorization_endpoint'] = authorizationEndpoint;
        obj['token_endpoint'] = tokenEndpoint;
        obj['registration_endpoint'] = registrationEndpoint;
        obj['response_types_supported'] = responseTypesSupported;
        obj['grant_types_supported'] = grantTypesSupported;
        obj['code_challenge_methods_supported'] = codeChallengeMethodsSupported;
    }

    /**
     * Constructs a <code>MCPOAuthServerMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MCPOAuthServerMetadata} obj Optional instance to populate.
     * @return {module:model/MCPOAuthServerMetadata} The populated <code>MCPOAuthServerMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MCPOAuthServerMetadata();

            if (data.hasOwnProperty('issuer')) {
                obj['issuer'] = ApiClient.convertToType(data['issuer'], 'String');
            }
            if (data.hasOwnProperty('authorization_endpoint')) {
                obj['authorization_endpoint'] = ApiClient.convertToType(data['authorization_endpoint'], 'String');
            }
            if (data.hasOwnProperty('token_endpoint')) {
                obj['token_endpoint'] = ApiClient.convertToType(data['token_endpoint'], 'String');
            }
            if (data.hasOwnProperty('registration_endpoint')) {
                obj['registration_endpoint'] = ApiClient.convertToType(data['registration_endpoint'], 'String');
            }
            if (data.hasOwnProperty('response_types_supported')) {
                obj['response_types_supported'] = ApiClient.convertToType(data['response_types_supported'], ['String']);
            }
            if (data.hasOwnProperty('grant_types_supported')) {
                obj['grant_types_supported'] = ApiClient.convertToType(data['grant_types_supported'], ['String']);
            }
            if (data.hasOwnProperty('code_challenge_methods_supported')) {
                obj['code_challenge_methods_supported'] = ApiClient.convertToType(data['code_challenge_methods_supported'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * The authorization server's issuer identifier (its base URL).
 * @member {String} issuer
 */
MCPOAuthServerMetadata.prototype['issuer'] = undefined;

/**
 * URL of the authorization endpoint.
 * @member {String} authorization_endpoint
 */
MCPOAuthServerMetadata.prototype['authorization_endpoint'] = undefined;

/**
 * URL of the token endpoint.
 * @member {String} token_endpoint
 */
MCPOAuthServerMetadata.prototype['token_endpoint'] = undefined;

/**
 * URL of the client registration endpoint.
 * @member {String} registration_endpoint
 */
MCPOAuthServerMetadata.prototype['registration_endpoint'] = undefined;

/**
 * List of supported OAuth2 response types.
 * @member {Array.<String>} response_types_supported
 */
MCPOAuthServerMetadata.prototype['response_types_supported'] = undefined;

/**
 * List of supported OAuth2 grant types.
 * @member {Array.<String>} grant_types_supported
 */
MCPOAuthServerMetadata.prototype['grant_types_supported'] = undefined;

/**
 * List of supported PKCE code challenge methods.
 * @member {Array.<String>} code_challenge_methods_supported
 */
MCPOAuthServerMetadata.prototype['code_challenge_methods_supported'] = undefined;






export default MCPOAuthServerMetadata;

