/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MCPOAuthTokenRequest model module.
 * @module model/MCPOAuthTokenRequest
 * @version 25.18.0
 */
class MCPOAuthTokenRequest {
    /**
     * Constructs a new <code>MCPOAuthTokenRequest</code>.
     * @alias module:model/MCPOAuthTokenRequest
     * @param grantType {module:model/MCPOAuthTokenRequest.GrantTypeEnum} OAuth2 grant type.
     */
    constructor(grantType) { 
        
        MCPOAuthTokenRequest.initialize(this, grantType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, grantType) { 
        obj['grant_type'] = grantType;
    }

    /**
     * Constructs a <code>MCPOAuthTokenRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MCPOAuthTokenRequest} obj Optional instance to populate.
     * @return {module:model/MCPOAuthTokenRequest} The populated <code>MCPOAuthTokenRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MCPOAuthTokenRequest();

            if (data.hasOwnProperty('grant_type')) {
                obj['grant_type'] = ApiClient.convertToType(data['grant_type'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('redirect_uri')) {
                obj['redirect_uri'] = ApiClient.convertToType(data['redirect_uri'], 'String');
            }
            if (data.hasOwnProperty('code_verifier')) {
                obj['code_verifier'] = ApiClient.convertToType(data['code_verifier'], 'String');
            }
            if (data.hasOwnProperty('refresh_token')) {
                obj['refresh_token'] = ApiClient.convertToType(data['refresh_token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * OAuth2 grant type.
 * @member {module:model/MCPOAuthTokenRequest.GrantTypeEnum} grant_type
 */
MCPOAuthTokenRequest.prototype['grant_type'] = undefined;

/**
 * Authorization code. Required for `authorization_code` grant.
 * @member {String} code
 */
MCPOAuthTokenRequest.prototype['code'] = undefined;

/**
 * Client ID. Required for `authorization_code` grant.
 * @member {String} client_id
 */
MCPOAuthTokenRequest.prototype['client_id'] = undefined;

/**
 * Redirect URI. Required for `authorization_code` grant.
 * @member {String} redirect_uri
 */
MCPOAuthTokenRequest.prototype['redirect_uri'] = undefined;

/**
 * PKCE code verifier. Required for `authorization_code` grant.
 * @member {String} code_verifier
 */
MCPOAuthTokenRequest.prototype['code_verifier'] = undefined;

/**
 * Refresh token. Required for `refresh_token` grant.
 * @member {String} refresh_token
 */
MCPOAuthTokenRequest.prototype['refresh_token'] = undefined;





/**
 * Allowed values for the <code>grant_type</code> property.
 * @enum {String}
 * @readonly
 */
MCPOAuthTokenRequest['GrantTypeEnum'] = {

    /**
     * value: "authorization_code"
     * @const
     */
    "authorization_code": "authorization_code",

    /**
     * value: "refresh_token"
     * @const
     */
    "refresh_token": "refresh_token"
};



export default MCPOAuthTokenRequest;

