/**
 * Talon.One API
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TalonOne) {
      root.TalonOne = {};
    }
    root.TalonOne.NewAttribute = factory(root.TalonOne.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The NewAttribute model module.
   * @module model/NewAttribute
   * @version 3.4.0
   */

  /**
   * Constructs a new <code>NewAttribute</code>.
   * 
   * @alias module:model/NewAttribute
   * @class
   * @param entity {module:model/NewAttribute.EntityEnum} The name of the entity that can have this attribute. When creating or updating the entities of a given type, you can include an `attributes` object with keys corresponding to the `name` of the custom attributes for that type.
   * @param name {String} The attribute name that will be used in API requests and Talang. E.g. if `name == \"region\"` then you would set the region attribute by including an `attributes.region` property in your request payload. 
   * @param title {String} The human-readable name for the attribute that will be shown in the Campaign Manager. Like `name`, the combination of entity and title must also be unique.
   * @param type {module:model/NewAttribute.TypeEnum} The data type of the attribute, a `time` attribute must be sent as a string that conforms to the [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) timestamp format.
   * @param description {String} A description of this attribute.
   * @param suggestions {Array.<String>} A list of suggestions for the attribute.
   * @param editable {Boolean} Whether or not this attribute can be edited.
   */
  var exports = function(entity, name, title, type, description, suggestions, editable) {
    var _this = this;

    _this['entity'] = entity;

    _this['name'] = name;
    _this['title'] = title;
    _this['type'] = type;
    _this['description'] = description;
    _this['suggestions'] = suggestions;
    _this['editable'] = editable;
  };

  /**
   * Constructs a <code>NewAttribute</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NewAttribute} obj Optional instance to populate.
   * @return {module:model/NewAttribute} The populated <code>NewAttribute</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('entity')) {
        obj['entity'] = ApiClient.convertToType(data['entity'], 'String');
      }
      if (data.hasOwnProperty('eventType')) {
        obj['eventType'] = ApiClient.convertToType(data['eventType'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('suggestions')) {
        obj['suggestions'] = ApiClient.convertToType(data['suggestions'], ['String']);
      }
      if (data.hasOwnProperty('editable')) {
        obj['editable'] = ApiClient.convertToType(data['editable'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * The name of the entity that can have this attribute. When creating or updating the entities of a given type, you can include an `attributes` object with keys corresponding to the `name` of the custom attributes for that type.
   * @member {module:model/NewAttribute.EntityEnum} entity
   */
  exports.prototype['entity'] = undefined;
  /**
   * @member {String} eventType
   */
  exports.prototype['eventType'] = undefined;
  /**
   * The attribute name that will be used in API requests and Talang. E.g. if `name == \"region\"` then you would set the region attribute by including an `attributes.region` property in your request payload. 
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The human-readable name for the attribute that will be shown in the Campaign Manager. Like `name`, the combination of entity and title must also be unique.
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * The data type of the attribute, a `time` attribute must be sent as a string that conforms to the [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) timestamp format.
   * @member {module:model/NewAttribute.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * A description of this attribute.
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * A list of suggestions for the attribute.
   * @member {Array.<String>} suggestions
   */
  exports.prototype['suggestions'] = undefined;
  /**
   * Whether or not this attribute can be edited.
   * @member {Boolean} editable
   */
  exports.prototype['editable'] = undefined;


  /**
   * Allowed values for the <code>entity</code> property.
   * @enum {String}
   * @readonly
   */
  exports.EntityEnum = {
    /**
     * value: "Account"
     * @const
     */
    "Account": "Account",
    /**
     * value: "Application"
     * @const
     */
    "Application": "Application",
    /**
     * value: "Campaign"
     * @const
     */
    "Campaign": "Campaign",
    /**
     * value: "CustomerProfile"
     * @const
     */
    "CustomerProfile": "CustomerProfile",
    /**
     * value: "CustomerSession"
     * @const
     */
    "CustomerSession": "CustomerSession",
    /**
     * value: "CartItem"
     * @const
     */
    "CartItem": "CartItem",
    /**
     * value: "Coupon"
     * @const
     */
    "Coupon": "Coupon",
    /**
     * value: "Event"
     * @const
     */
    "Event": "Event"  };

  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "string"
     * @const
     */
    "string": "string",
    /**
     * value: "number"
     * @const
     */
    "number": "number",
    /**
     * value: "boolean"
     * @const
     */
    "boolean": "boolean",
    /**
     * value: "time"
     * @const
     */
    "time": "time",
    /**
     * value: "(list string)"
     * @const
     */
    "(list string)": "(list string)",
    /**
     * value: "(list number)"
     * @const
     */
    "(list number)": "(list number)",
    /**
     * value: "(list time)"
     * @const
     */
    "(list time)": "(list time)",
    /**
     * value: "location"
     * @const
     */
    "location": "location",
    /**
     * value: "(list location)"
     * @const
     */
    "(list location)": "(list location)"  };


  return exports;
}));


