/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TemplateArgDef from './TemplateArgDef';

/**
 * The NewMessageTest model module.
 * @module model/NewMessageTest
 * @version 25.16.0
 */
class NewMessageTest {
    /**
     * Constructs a new <code>NewMessageTest</code>.
     * @alias module:model/NewMessageTest
     * @param verb {module:model/NewMessageTest.VerbEnum} API method for this message.
     * @param url {String} API URL for the given message.
     */
    constructor(verb, url) { 
        
        NewMessageTest.initialize(this, verb, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, verb, url) { 
        obj['verb'] = verb;
        obj['url'] = url;
    }

    /**
     * Constructs a <code>NewMessageTest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewMessageTest} obj Optional instance to populate.
     * @return {module:model/NewMessageTest} The populated <code>NewMessageTest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewMessageTest();

            if (data.hasOwnProperty('headers')) {
                obj['headers'] = ApiClient.convertToType(data['headers'], {'String': 'String'});
            }
            if (data.hasOwnProperty('verb')) {
                obj['verb'] = ApiClient.convertToType(data['verb'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = ApiClient.convertToType(data['payload'], 'String');
            }
            if (data.hasOwnProperty('params')) {
                obj['params'] = ApiClient.convertToType(data['params'], [TemplateArgDef]);
            }
            if (data.hasOwnProperty('applicationIds')) {
                obj['applicationIds'] = ApiClient.convertToType(data['applicationIds'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * List of API HTTP headers for the given message.
 * @member {Object.<String, String>} headers
 */
NewMessageTest.prototype['headers'] = undefined;

/**
 * API method for this message.
 * @member {module:model/NewMessageTest.VerbEnum} verb
 */
NewMessageTest.prototype['verb'] = undefined;

/**
 * API URL for the given message.
 * @member {String} url
 */
NewMessageTest.prototype['url'] = undefined;

/**
 * API payload of this message.
 * @member {String} payload
 */
NewMessageTest.prototype['payload'] = undefined;

/**
 * Array of template argument definitions.
 * @member {Array.<module:model/TemplateArgDef>} params
 */
NewMessageTest.prototype['params'] = undefined;

/**
 * The IDs of the Applications in which this webhook is available. An empty array means the webhook is available in `All Applications`. 
 * @member {Array.<Number>} applicationIds
 */
NewMessageTest.prototype['applicationIds'] = undefined;





/**
 * Allowed values for the <code>verb</code> property.
 * @enum {String}
 * @readonly
 */
NewMessageTest['VerbEnum'] = {

    /**
     * value: "POST"
     * @const
     */
    "POST": "POST",

    /**
     * value: "PUT"
     * @const
     */
    "PUT": "PUT",

    /**
     * value: "GET"
     * @const
     */
    "GET": "GET",

    /**
     * value: "DELETE"
     * @const
     */
    "DELETE": "DELETE",

    /**
     * value: "PATCH"
     * @const
     */
    "PATCH": "PATCH"
};



export default NewMessageTest;

