/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NewReward model module.
 * @module model/NewReward
 * @version 25.17.0
 */
class NewReward {
    /**
     * Constructs a new <code>NewReward</code>.
     * @alias module:model/NewReward
     * @param name {String} The name of the reward.
     * @param apiName {String} A unique identifier used to reference the reward in API integrations.
     * @param applicationIds {Array.<Number>} The IDs of the Applications this reward is connected to.   **Note**: Currently, a reward can only be connected to one Application. 
     * @param sandbox {Boolean} Indicates if this is a live or sandbox reward. Rewards of a given type can only be connected to Applications of the same type.
     */
    constructor(name, apiName, applicationIds, sandbox) { 
        
        NewReward.initialize(this, name, apiName, applicationIds, sandbox);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, apiName, applicationIds, sandbox) { 
        obj['name'] = name;
        obj['apiName'] = apiName;
        obj['applicationIds'] = applicationIds;
        obj['sandbox'] = sandbox;
    }

    /**
     * Constructs a <code>NewReward</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewReward} obj Optional instance to populate.
     * @return {module:model/NewReward} The populated <code>NewReward</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewReward();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('apiName')) {
                obj['apiName'] = ApiClient.convertToType(data['apiName'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('applicationIds')) {
                obj['applicationIds'] = ApiClient.convertToType(data['applicationIds'], ['Number']);
            }
            if (data.hasOwnProperty('sandbox')) {
                obj['sandbox'] = ApiClient.convertToType(data['sandbox'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * The name of the reward.
 * @member {String} name
 */
NewReward.prototype['name'] = undefined;

/**
 * A unique identifier used to reference the reward in API integrations.
 * @member {String} apiName
 */
NewReward.prototype['apiName'] = undefined;

/**
 * A description of the reward.
 * @member {String} description
 */
NewReward.prototype['description'] = undefined;

/**
 * The IDs of the Applications this reward is connected to.   **Note**: Currently, a reward can only be connected to one Application. 
 * @member {Array.<Number>} applicationIds
 */
NewReward.prototype['applicationIds'] = undefined;

/**
 * Indicates if this is a live or sandbox reward. Rewards of a given type can only be connected to Applications of the same type.
 * @member {Boolean} sandbox
 */
NewReward.prototype['sandbox'] = undefined;






export default NewReward;

