/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TemplateArgDef from './TemplateArgDef';

/**
 * The NewWebhook model module.
 * @module model/NewWebhook
 * @version 8.0.0
 */
class NewWebhook {
    /**
     * Constructs a new <code>NewWebhook</code>.
     * 
     * @alias module:model/NewWebhook
     * @param applicationIds {Array.<Number>} The IDs of the Applications that are related to this entity.
     * @param title {String} Name or title for this webhook.
     * @param verb {module:model/NewWebhook.VerbEnum} API method for this webhook.
     * @param url {String} API URL (supports templating using parameters) for this webhook.
     * @param headers {Array.<String>} List of API HTTP headers for this webhook.
     * @param params {Array.<module:model/TemplateArgDef>} Array of template argument definitions.
     * @param enabled {Boolean} Enables or disables webhook from showing in the Rule Builder.
     */
    constructor(applicationIds, title, verb, url, headers, params, enabled) { 
        
        NewWebhook.initialize(this, applicationIds, title, verb, url, headers, params, enabled);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, applicationIds, title, verb, url, headers, params, enabled) { 
        obj['applicationIds'] = applicationIds;
        obj['title'] = title;
        obj['verb'] = verb;
        obj['url'] = url;
        obj['headers'] = headers;
        obj['params'] = params;
        obj['enabled'] = enabled;
    }

    /**
     * Constructs a <code>NewWebhook</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewWebhook} obj Optional instance to populate.
     * @return {module:model/NewWebhook} The populated <code>NewWebhook</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewWebhook();

            if (data.hasOwnProperty('applicationIds')) {
                obj['applicationIds'] = ApiClient.convertToType(data['applicationIds'], ['Number']);
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('verb')) {
                obj['verb'] = ApiClient.convertToType(data['verb'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('headers')) {
                obj['headers'] = ApiClient.convertToType(data['headers'], ['String']);
            }
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = ApiClient.convertToType(data['payload'], 'String');
            }
            if (data.hasOwnProperty('params')) {
                obj['params'] = ApiClient.convertToType(data['params'], [TemplateArgDef]);
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * The IDs of the Applications that are related to this entity.
 * @member {Array.<Number>} applicationIds
 */
NewWebhook.prototype['applicationIds'] = undefined;

/**
 * Name or title for this webhook.
 * @member {String} title
 */
NewWebhook.prototype['title'] = undefined;

/**
 * API method for this webhook.
 * @member {module:model/NewWebhook.VerbEnum} verb
 */
NewWebhook.prototype['verb'] = undefined;

/**
 * API URL (supports templating using parameters) for this webhook.
 * @member {String} url
 */
NewWebhook.prototype['url'] = undefined;

/**
 * List of API HTTP headers for this webhook.
 * @member {Array.<String>} headers
 */
NewWebhook.prototype['headers'] = undefined;

/**
 * API payload (supports templating using parameters) for this webhook.
 * @member {String} payload
 */
NewWebhook.prototype['payload'] = undefined;

/**
 * Array of template argument definitions.
 * @member {Array.<module:model/TemplateArgDef>} params
 */
NewWebhook.prototype['params'] = undefined;

/**
 * Enables or disables webhook from showing in the Rule Builder.
 * @member {Boolean} enabled
 */
NewWebhook.prototype['enabled'] = undefined;





/**
 * Allowed values for the <code>verb</code> property.
 * @enum {String}
 * @readonly
 */
NewWebhook['VerbEnum'] = {

    /**
     * value: "POST"
     * @const
     */
    "POST": "POST",

    /**
     * value: "PUT"
     * @const
     */
    "PUT": "PUT",

    /**
     * value: "GET"
     * @const
     */
    "GET": "GET",

    /**
     * value: "DELETE"
     * @const
     */
    "DELETE": "DELETE",

    /**
     * value: "PATCH"
     * @const
     */
    "PATCH": "PATCH"
};



export default NewWebhook;

