/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PriceTypeReferenceDetail model module.
 * @module model/PriceTypeReferenceDetail
 * @version 25.16.0
 */
class PriceTypeReferenceDetail {
    /**
     * Constructs a new <code>PriceTypeReferenceDetail</code>.
     * @alias module:model/PriceTypeReferenceDetail
     * @param referencingType {module:model/PriceTypeReferenceDetail.ReferencingTypeEnum} The entity type that references the price type. For example, a campaign or an Application cart item filter.
     * @param referencingId {Number} The ID of the entity that references the price type.
     * @param referencingName {String} The name of the entity that references the price type.
     */
    constructor(referencingType, referencingId, referencingName) { 
        
        PriceTypeReferenceDetail.initialize(this, referencingType, referencingId, referencingName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, referencingType, referencingId, referencingName) { 
        obj['referencingType'] = referencingType;
        obj['referencingId'] = referencingId;
        obj['referencingName'] = referencingName;
    }

    /**
     * Constructs a <code>PriceTypeReferenceDetail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PriceTypeReferenceDetail} obj Optional instance to populate.
     * @return {module:model/PriceTypeReferenceDetail} The populated <code>PriceTypeReferenceDetail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PriceTypeReferenceDetail();

            if (data.hasOwnProperty('referencingType')) {
                obj['referencingType'] = ApiClient.convertToType(data['referencingType'], 'String');
            }
            if (data.hasOwnProperty('referencingId')) {
                obj['referencingId'] = ApiClient.convertToType(data['referencingId'], 'Number');
            }
            if (data.hasOwnProperty('referencingName')) {
                obj['referencingName'] = ApiClient.convertToType(data['referencingName'], 'String');
            }
            if (data.hasOwnProperty('applicationId')) {
                obj['applicationId'] = ApiClient.convertToType(data['applicationId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The entity type that references the price type. For example, a campaign or an Application cart item filter.
 * @member {module:model/PriceTypeReferenceDetail.ReferencingTypeEnum} referencingType
 */
PriceTypeReferenceDetail.prototype['referencingType'] = undefined;

/**
 * The ID of the entity that references the price type.
 * @member {Number} referencingId
 */
PriceTypeReferenceDetail.prototype['referencingId'] = undefined;

/**
 * The name of the entity that references the price type.
 * @member {String} referencingName
 */
PriceTypeReferenceDetail.prototype['referencingName'] = undefined;

/**
 * The ID of the Application that contains the entity that references the price type.
 * @member {Number} applicationId
 */
PriceTypeReferenceDetail.prototype['applicationId'] = undefined;





/**
 * Allowed values for the <code>referencingType</code> property.
 * @enum {String}
 * @readonly
 */
PriceTypeReferenceDetail['ReferencingTypeEnum'] = {

    /**
     * value: "Campaign"
     * @const
     */
    "Campaign": "Campaign",

    /**
     * value: "ApplicationCartItemFilter"
     * @const
     */
    "ApplicationCartItemFilter": "ApplicationCartItemFilter",

    /**
     * value: "Template"
     * @const
     */
    "Template": "Template"
};



export default PriceTypeReferenceDetail;

