/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Effect from './Effect';

/**
 * The ReopenSessionResponse model module.
 * @module model/ReopenSessionResponse
 * @version .0
 */
class ReopenSessionResponse {
    /**
     * Constructs a new <code>ReopenSessionResponse</code>.
     * This is the response type returned by the Reopen customer sessions endpoint. It contains the rolled back effects. 
     * @alias module:model/ReopenSessionResponse
     * @param effects {Array.<module:model/Effect>} The effects generated by the rules in your running campaigns. See [API effects](https://docs.talon.one/docs/dev/integration-api/api-effects).
     */
    constructor(effects) { 
        
        ReopenSessionResponse.initialize(this, effects);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, effects) { 
        obj['effects'] = effects;
    }

    /**
     * Constructs a <code>ReopenSessionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReopenSessionResponse} obj Optional instance to populate.
     * @return {module:model/ReopenSessionResponse} The populated <code>ReopenSessionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReopenSessionResponse();

            if (data.hasOwnProperty('effects')) {
                obj['effects'] = ApiClient.convertToType(data['effects'], [Effect]);
            }
        }
        return obj;
    }


}

/**
 * The effects generated by the rules in your running campaigns. See [API effects](https://docs.talon.one/docs/dev/integration-api/api-effects).
 * @member {Array.<module:model/Effect>} effects
 */
ReopenSessionResponse.prototype['effects'] = undefined;






export default ReopenSessionResponse;

