/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SamlConnectionMetadata model module.
 * @module model/SamlConnectionMetadata
 * @version 25.16.0
 */
class SamlConnectionMetadata {
    /**
     * Constructs a new <code>SamlConnectionMetadata</code>.
     * @alias module:model/SamlConnectionMetadata
     * @param name {String} ID of the SAML service.
     * @param enabled {Boolean} Determines if this SAML connection active.
     * @param accountId {Number} 
     * @param metadataDocument {String} Identity Provider metadata XML document.
     */
    constructor(name, enabled, accountId, metadataDocument) { 
        
        SamlConnectionMetadata.initialize(this, name, enabled, accountId, metadataDocument);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, enabled, accountId, metadataDocument) { 
        obj['name'] = name;
        obj['enabled'] = enabled;
        obj['accountId'] = accountId;
        obj['metadataDocument'] = metadataDocument;
    }

    /**
     * Constructs a <code>SamlConnectionMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SamlConnectionMetadata} obj Optional instance to populate.
     * @return {module:model/SamlConnectionMetadata} The populated <code>SamlConnectionMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SamlConnectionMetadata();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('accountId')) {
                obj['accountId'] = ApiClient.convertToType(data['accountId'], 'Number');
            }
            if (data.hasOwnProperty('metadataDocument')) {
                obj['metadataDocument'] = ApiClient.convertToType(data['metadataDocument'], 'String');
            }
        }
        return obj;
    }


}

/**
 * ID of the SAML service.
 * @member {String} name
 */
SamlConnectionMetadata.prototype['name'] = undefined;

/**
 * Determines if this SAML connection active.
 * @member {Boolean} enabled
 */
SamlConnectionMetadata.prototype['enabled'] = undefined;

/**
 * @member {Number} accountId
 */
SamlConnectionMetadata.prototype['accountId'] = undefined;

/**
 * Identity Provider metadata XML document.
 * @member {String} metadataDocument
 */
SamlConnectionMetadata.prototype['metadataDocument'] = undefined;






export default SamlConnectionMetadata;

