/**
 * Talon.One API
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SetDiscountPerItemEffectProps model module.
 * @module model/SetDiscountPerItemEffectProps
 * @version 4.4.0
 */
class SetDiscountPerItemEffectProps {
    /**
     * Constructs a new <code>SetDiscountPerItemEffectProps</code>.
     * The properties specific to the \&quot;setDiscountPerItem\&quot; effect. This gets triggered whenever a validated rule contained a \&quot;set per item discount\&quot; effect. This is a discount that should be applied on a specific item.
     * @alias module:model/SetDiscountPerItemEffectProps
     * @param name {String} The name/description of this discount
     * @param value {Number} The total monetary value of the discount
     * @param position {Number} The index of the item in the cart items list on which this discount should be applied
     */
    constructor(name, value, position) { 
        
        SetDiscountPerItemEffectProps.initialize(this, name, value, position);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, value, position) { 
        obj['name'] = name;
        obj['value'] = value;
        obj['position'] = position;
    }

    /**
     * Constructs a <code>SetDiscountPerItemEffectProps</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SetDiscountPerItemEffectProps} obj Optional instance to populate.
     * @return {module:model/SetDiscountPerItemEffectProps} The populated <code>SetDiscountPerItemEffectProps</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetDiscountPerItemEffectProps();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'Number');
            }
            if (data.hasOwnProperty('subPosition')) {
                obj['subPosition'] = ApiClient.convertToType(data['subPosition'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The name/description of this discount
 * @member {String} name
 */
SetDiscountPerItemEffectProps.prototype['name'] = undefined;

/**
 * The total monetary value of the discount
 * @member {Number} value
 */
SetDiscountPerItemEffectProps.prototype['value'] = undefined;

/**
 * The index of the item in the cart items list on which this discount should be applied
 * @member {Number} position
 */
SetDiscountPerItemEffectProps.prototype['position'] = undefined;

/**
 * The sub-index of the item in an item stack on which this discount should be applied
 * @member {Number} subPosition
 */
SetDiscountPerItemEffectProps.prototype['subPosition'] = undefined;






export default SetDiscountPerItemEffectProps;

