/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateSupportRequest model module.
 * @module model/UpdateSupportRequest
 * @version 25.18.0
 */
class UpdateSupportRequest {
    /**
     * Constructs a new <code>UpdateSupportRequest</code>.
     * @alias module:model/UpdateSupportRequest
     * @param requestStatus {module:model/UpdateSupportRequest.RequestStatusEnum} Current status of the support request.
     */
    constructor(requestStatus) { 
        
        UpdateSupportRequest.initialize(this, requestStatus);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, requestStatus) { 
        obj['requestStatus'] = requestStatus;
    }

    /**
     * Constructs a <code>UpdateSupportRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateSupportRequest} obj Optional instance to populate.
     * @return {module:model/UpdateSupportRequest} The populated <code>UpdateSupportRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateSupportRequest();

            if (data.hasOwnProperty('requestStatus')) {
                obj['requestStatus'] = ApiClient.convertToType(data['requestStatus'], 'String');
            }
            if (data.hasOwnProperty('processingNote')) {
                obj['processingNote'] = ApiClient.convertToType(data['processingNote'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Current status of the support request.
 * @member {module:model/UpdateSupportRequest.RequestStatusEnum} requestStatus
 */
UpdateSupportRequest.prototype['requestStatus'] = undefined;

/**
 * Notes attached by the admin when rejecting or approving a request.
 * @member {String} processingNote
 */
UpdateSupportRequest.prototype['processingNote'] = undefined;





/**
 * Allowed values for the <code>requestStatus</code> property.
 * @enum {String}
 * @readonly
 */
UpdateSupportRequest['RequestStatusEnum'] = {

    /**
     * value: "approved"
     * @const
     */
    "approved": "approved",

    /**
     * value: "rejected"
     * @const
     */
    "rejected": "rejected",

    /**
     * value: "expired"
     * @const
     */
    "expired": "expired"
};



export default UpdateSupportRequest;

