/**
 * Talon.One API
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateReferralBatch model module.
 * @module model/UpdateReferralBatch
 * @version 4.4.0
 */
class UpdateReferralBatch {
    /**
     * Constructs a new <code>UpdateReferralBatch</code>.
     * @alias module:model/UpdateReferralBatch
     * @param batchID {String} The id of the batch the referral belongs to.
     */
    constructor(batchID) { 
        
        UpdateReferralBatch.initialize(this, batchID);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, batchID) { 
        obj['batchID'] = batchID;
    }

    /**
     * Constructs a <code>UpdateReferralBatch</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateReferralBatch} obj Optional instance to populate.
     * @return {module:model/UpdateReferralBatch} The populated <code>UpdateReferralBatch</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateReferralBatch();

            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], Object);
            }
            if (data.hasOwnProperty('batchID')) {
                obj['batchID'] = ApiClient.convertToType(data['batchID'], 'String');
            }
            if (data.hasOwnProperty('startDate')) {
                obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
            }
            if (data.hasOwnProperty('expiryDate')) {
                obj['expiryDate'] = ApiClient.convertToType(data['expiryDate'], 'Date');
            }
            if (data.hasOwnProperty('usageLimit')) {
                obj['usageLimit'] = ApiClient.convertToType(data['usageLimit'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Arbitrary properties associated with this item
 * @member {Object} attributes
 */
UpdateReferralBatch.prototype['attributes'] = undefined;

/**
 * The id of the batch the referral belongs to.
 * @member {String} batchID
 */
UpdateReferralBatch.prototype['batchID'] = undefined;

/**
 * Timestamp at which point the referral code becomes valid.
 * @member {Date} startDate
 */
UpdateReferralBatch.prototype['startDate'] = undefined;

/**
 * Expiry date of the referral code. Referral never expires if this is omitted, zero, or negative.
 * @member {Date} expiryDate
 */
UpdateReferralBatch.prototype['expiryDate'] = undefined;

/**
 * The number of times a referral code can be used. This can be set to 0 for no limit, but any campaign usage limits will still apply. 
 * @member {Number} usageLimit
 */
UpdateReferralBatch.prototype['usageLimit'] = undefined;






export default UpdateReferralBatch;

