/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TalonOne);
  }
}(this, function(expect, TalonOne) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TalonOne.TierWillDowngradeData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TierWillDowngradeData', function() {
    it('should create an instance of TierWillDowngradeData', function() {
      // uncomment below and update the code to test TierWillDowngradeData
      //var instane = new TalonOne.TierWillDowngradeData();
      //expect(instance).to.be.a(TalonOne.TierWillDowngradeData);
    });

    it('should have the property customerProfileID (base name: "CustomerProfileID")', function() {
      // uncomment below and update the code to test the property customerProfileID
      //var instane = new TalonOne.TierWillDowngradeData();
      //expect(instance).to.be();
    });

    it('should have the property loyaltyProgramID (base name: "LoyaltyProgramID")', function() {
      // uncomment below and update the code to test the property loyaltyProgramID
      //var instane = new TalonOne.TierWillDowngradeData();
      //expect(instance).to.be();
    });

    it('should have the property subledgerID (base name: "SubledgerID")', function() {
      // uncomment below and update the code to test the property subledgerID
      //var instane = new TalonOne.TierWillDowngradeData();
      //expect(instance).to.be();
    });

    it('should have the property currentTier (base name: "CurrentTier")', function() {
      // uncomment below and update the code to test the property currentTier
      //var instane = new TalonOne.TierWillDowngradeData();
      //expect(instance).to.be();
    });

    it('should have the property currentPoints (base name: "CurrentPoints")', function() {
      // uncomment below and update the code to test the property currentPoints
      //var instane = new TalonOne.TierWillDowngradeData();
      //expect(instance).to.be();
    });

    it('should have the property pointsRequiredToRemain (base name: "PointsRequiredToRemain")', function() {
      // uncomment below and update the code to test the property pointsRequiredToRemain
      //var instane = new TalonOne.TierWillDowngradeData();
      //expect(instance).to.be();
    });

    it('should have the property nextTier (base name: "NextTier")', function() {
      // uncomment below and update the code to test the property nextTier
      //var instane = new TalonOne.TierWillDowngradeData();
      //expect(instance).to.be();
    });

    it('should have the property tierExpirationDate (base name: "TierExpirationDate")', function() {
      // uncomment below and update the code to test the property tierExpirationDate
      //var instane = new TalonOne.TierWillDowngradeData();
      //expect(instance).to.be();
    });

  });

}));
