/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://mycompany.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import APIError from './model/APIError';
import AcceptCouponEffectProps from './model/AcceptCouponEffectProps';
import AcceptReferralEffectProps from './model/AcceptReferralEffectProps';
import AccessLogEntry from './model/AccessLogEntry';
import Account from './model/Account';
import AccountAdditionalCost from './model/AccountAdditionalCost';
import AccountAnalytics from './model/AccountAnalytics';
import AccountDashboardStatistic from './model/AccountDashboardStatistic';
import AccountDashboardStatisticApiCalls from './model/AccountDashboardStatisticApiCalls';
import AccountDashboardStatisticCampaigns from './model/AccountDashboardStatisticCampaigns';
import AccountDashboardStatisticDiscount from './model/AccountDashboardStatisticDiscount';
import AccountDashboardStatisticLoyaltyPoints from './model/AccountDashboardStatisticLoyaltyPoints';
import AccountDashboardStatisticReferrals from './model/AccountDashboardStatisticReferrals';
import AccountDashboardStatisticRevenue from './model/AccountDashboardStatisticRevenue';
import AccountEntity from './model/AccountEntity';
import AccountLimits from './model/AccountLimits';
import AddFreeItemEffectProps from './model/AddFreeItemEffectProps';
import AddItemCatalogAction from './model/AddItemCatalogAction';
import AddLoyaltyPoints from './model/AddLoyaltyPoints';
import AddLoyaltyPointsEffectProps from './model/AddLoyaltyPointsEffectProps';
import AddedDeductedPointsNotificationPolicy from './model/AddedDeductedPointsNotificationPolicy';
import AdditionalCost from './model/AdditionalCost';
import Application from './model/Application';
import ApplicationAPIKey from './model/ApplicationAPIKey';
import ApplicationApiHealth from './model/ApplicationApiHealth';
import ApplicationCampaignStats from './model/ApplicationCampaignStats';
import ApplicationCustomer from './model/ApplicationCustomer';
import ApplicationCustomerEntity from './model/ApplicationCustomerEntity';
import ApplicationEntity from './model/ApplicationEntity';
import ApplicationEvent from './model/ApplicationEvent';
import ApplicationNotification from './model/ApplicationNotification';
import ApplicationReferee from './model/ApplicationReferee';
import ApplicationSession from './model/ApplicationSession';
import ApplicationSessionEntity from './model/ApplicationSessionEntity';
import AsyncCouponCreationResponse from './model/AsyncCouponCreationResponse';
import Attribute from './model/Attribute';
import AttributesMandatory from './model/AttributesMandatory';
import AttributesSettings from './model/AttributesSettings';
import Audience from './model/Audience';
import AudienceAnalytics from './model/AudienceAnalytics';
import AudienceCustomer from './model/AudienceCustomer';
import AudienceIntegrationID from './model/AudienceIntegrationID';
import AudienceMembership from './model/AudienceMembership';
import AwardGiveawayEffectProps from './model/AwardGiveawayEffectProps';
import BaseLoyaltyProgram from './model/BaseLoyaltyProgram';
import BaseNotification from './model/BaseNotification';
import BaseNotificationEntity from './model/BaseNotificationEntity';
import BaseNotificationWebhook from './model/BaseNotificationWebhook';
import BaseNotifications from './model/BaseNotifications';
import BaseSamlConnection from './model/BaseSamlConnection';
import Binding from './model/Binding';
import BulkApplicationNotification from './model/BulkApplicationNotification';
import BulkCampaignNotification from './model/BulkCampaignNotification';
import Campaign from './model/Campaign';
import CampaignActivationRequest from './model/CampaignActivationRequest';
import CampaignAnalytics from './model/CampaignAnalytics';
import CampaignCollection from './model/CampaignCollection';
import CampaignCollectionWithoutPayload from './model/CampaignCollectionWithoutPayload';
import CampaignCopy from './model/CampaignCopy';
import CampaignCreatedNotification from './model/CampaignCreatedNotification';
import CampaignDeletedNotification from './model/CampaignDeletedNotification';
import CampaignEditedNotification from './model/CampaignEditedNotification';
import CampaignEntity from './model/CampaignEntity';
import CampaignGroup from './model/CampaignGroup';
import CampaignGroupEntity from './model/CampaignGroupEntity';
import CampaignNotification from './model/CampaignNotification';
import CampaignPrioritiesChangedNotification from './model/CampaignPrioritiesChangedNotification';
import CampaignPrioritiesV2 from './model/CampaignPrioritiesV2';
import CampaignRulesetChangedNotification from './model/CampaignRulesetChangedNotification';
import CampaignSearch from './model/CampaignSearch';
import CampaignSet from './model/CampaignSet';
import CampaignSetBranchNode from './model/CampaignSetBranchNode';
import CampaignSetIDs from './model/CampaignSetIDs';
import CampaignSetLeafNode from './model/CampaignSetLeafNode';
import CampaignSetNode from './model/CampaignSetNode';
import CampaignSetV2 from './model/CampaignSetV2';
import CampaignStateChangedNotification from './model/CampaignStateChangedNotification';
import CampaignTemplate from './model/CampaignTemplate';
import CampaignTemplateCollection from './model/CampaignTemplateCollection';
import CampaignTemplateParams from './model/CampaignTemplateParams';
import CardLedgerTransactionLogEntry from './model/CardLedgerTransactionLogEntry';
import CardLedgerTransactionLogEntryIntegrationAPI from './model/CardLedgerTransactionLogEntryIntegrationAPI';
import CartItem from './model/CartItem';
import Catalog from './model/Catalog';
import CatalogAction from './model/CatalogAction';
import CatalogActionFilter from './model/CatalogActionFilter';
import CatalogItem from './model/CatalogItem';
import CatalogSyncRequest from './model/CatalogSyncRequest';
import CatalogsStrikethroughNotificationPolicy from './model/CatalogsStrikethroughNotificationPolicy';
import Change from './model/Change';
import ChangeProfilePassword from './model/ChangeProfilePassword';
import CodeGeneratorSettings from './model/CodeGeneratorSettings';
import Collection from './model/Collection';
import CollectionItem from './model/CollectionItem';
import CollectionWithoutPayload from './model/CollectionWithoutPayload';
import Coupon from './model/Coupon';
import CouponConstraints from './model/CouponConstraints';
import CouponCreatedEffectProps from './model/CouponCreatedEffectProps';
import CouponCreationJob from './model/CouponCreationJob';
import CouponLimitConfigs from './model/CouponLimitConfigs';
import CouponRejectionReason from './model/CouponRejectionReason';
import CouponReservations from './model/CouponReservations';
import CouponSearch from './model/CouponSearch';
import CouponValue from './model/CouponValue';
import CouponsNotificationPolicy from './model/CouponsNotificationPolicy';
import CreateApplicationAPIKey from './model/CreateApplicationAPIKey';
import CreateManagementKey from './model/CreateManagementKey';
import CreateTemplateCampaign from './model/CreateTemplateCampaign';
import CreateTemplateCampaignResponse from './model/CreateTemplateCampaignResponse';
import CustomEffect from './model/CustomEffect';
import CustomEffectProps from './model/CustomEffectProps';
import CustomerActivityReport from './model/CustomerActivityReport';
import CustomerAnalytics from './model/CustomerAnalytics';
import CustomerInventory from './model/CustomerInventory';
import CustomerProfile from './model/CustomerProfile';
import CustomerProfileAudienceRequest from './model/CustomerProfileAudienceRequest';
import CustomerProfileAudienceRequestItem from './model/CustomerProfileAudienceRequestItem';
import CustomerProfileIntegrationRequestV2 from './model/CustomerProfileIntegrationRequestV2';
import CustomerProfileSearchQuery from './model/CustomerProfileSearchQuery';
import CustomerProfileUpdateV2Response from './model/CustomerProfileUpdateV2Response';
import CustomerSession from './model/CustomerSession';
import CustomerSessionV2 from './model/CustomerSessionV2';
import DeductLoyaltyPoints from './model/DeductLoyaltyPoints';
import DeductLoyaltyPointsEffectProps from './model/DeductLoyaltyPointsEffectProps';
import Effect from './model/Effect';
import EffectEntity from './model/EffectEntity';
import EmailEntity from './model/EmailEntity';
import Endpoint from './model/Endpoint';
import Entity from './model/Entity';
import EntityWithTalangVisibleID from './model/EntityWithTalangVisibleID';
import Environment from './model/Environment';
import ErrorEffectProps from './model/ErrorEffectProps';
import ErrorResponse from './model/ErrorResponse';
import ErrorResponseWithStatus from './model/ErrorResponseWithStatus';
import ErrorSource from './model/ErrorSource';
import EvaluableCampaignIds from './model/EvaluableCampaignIds';
import Event from './model/Event';
import EventType from './model/EventType';
import EventV2 from './model/EventV2';
import ExpiringPointsNotificationPolicy from './model/ExpiringPointsNotificationPolicy';
import ExpiringPointsNotificationTrigger from './model/ExpiringPointsNotificationTrigger';
import FeatureFlag from './model/FeatureFlag';
import FeaturesFeed from './model/FeaturesFeed';
import FeedNotification from './model/FeedNotification';
import FrontendState from './model/FrontendState';
import FuncArgDef from './model/FuncArgDef';
import FunctionDef from './model/FunctionDef';
import Giveaway from './model/Giveaway';
import GiveawaysPool from './model/GiveawaysPool';
import ImportEntity from './model/ImportEntity';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse20010 from './model/InlineResponse20010';
import InlineResponse20011 from './model/InlineResponse20011';
import InlineResponse20012 from './model/InlineResponse20012';
import InlineResponse20013 from './model/InlineResponse20013';
import InlineResponse20014 from './model/InlineResponse20014';
import InlineResponse20015 from './model/InlineResponse20015';
import InlineResponse20016 from './model/InlineResponse20016';
import InlineResponse20017 from './model/InlineResponse20017';
import InlineResponse20018 from './model/InlineResponse20018';
import InlineResponse20019 from './model/InlineResponse20019';
import InlineResponse2002 from './model/InlineResponse2002';
import InlineResponse20020 from './model/InlineResponse20020';
import InlineResponse20021 from './model/InlineResponse20021';
import InlineResponse20022 from './model/InlineResponse20022';
import InlineResponse20023 from './model/InlineResponse20023';
import InlineResponse20024 from './model/InlineResponse20024';
import InlineResponse20025 from './model/InlineResponse20025';
import InlineResponse20026 from './model/InlineResponse20026';
import InlineResponse20027 from './model/InlineResponse20027';
import InlineResponse20028 from './model/InlineResponse20028';
import InlineResponse20029 from './model/InlineResponse20029';
import InlineResponse2003 from './model/InlineResponse2003';
import InlineResponse20030 from './model/InlineResponse20030';
import InlineResponse20031 from './model/InlineResponse20031';
import InlineResponse20032 from './model/InlineResponse20032';
import InlineResponse20033 from './model/InlineResponse20033';
import InlineResponse20034 from './model/InlineResponse20034';
import InlineResponse20035 from './model/InlineResponse20035';
import InlineResponse20036 from './model/InlineResponse20036';
import InlineResponse20037 from './model/InlineResponse20037';
import InlineResponse20038 from './model/InlineResponse20038';
import InlineResponse20039 from './model/InlineResponse20039';
import InlineResponse2004 from './model/InlineResponse2004';
import InlineResponse2005 from './model/InlineResponse2005';
import InlineResponse2006 from './model/InlineResponse2006';
import InlineResponse2007 from './model/InlineResponse2007';
import InlineResponse2008 from './model/InlineResponse2008';
import InlineResponse2009 from './model/InlineResponse2009';
import InlineResponse201 from './model/InlineResponse201';
import IntegrationCoupon from './model/IntegrationCoupon';
import IntegrationCustomerSessionResponse from './model/IntegrationCustomerSessionResponse';
import IntegrationEntity from './model/IntegrationEntity';
import IntegrationEvent from './model/IntegrationEvent';
import IntegrationEventV2Request from './model/IntegrationEventV2Request';
import IntegrationProfileEntity from './model/IntegrationProfileEntity';
import IntegrationRequest from './model/IntegrationRequest';
import IntegrationState from './model/IntegrationState';
import IntegrationStateV2 from './model/IntegrationStateV2';
import InventoryCoupon from './model/InventoryCoupon';
import InventoryReferral from './model/InventoryReferral';
import ItemAttribute from './model/ItemAttribute';
import LedgerEntry from './model/LedgerEntry';
import LedgerInfo from './model/LedgerInfo';
import LedgerTransactionLogEntryIntegrationAPI from './model/LedgerTransactionLogEntryIntegrationAPI';
import LibraryAttribute from './model/LibraryAttribute';
import LimitConfig from './model/LimitConfig';
import LimitCounter from './model/LimitCounter';
import LoginParams from './model/LoginParams';
import Loyalty from './model/Loyalty';
import LoyaltyBalance from './model/LoyaltyBalance';
import LoyaltyBalances from './model/LoyaltyBalances';
import LoyaltyCard from './model/LoyaltyCard';
import LoyaltyCardProfileRegistration from './model/LoyaltyCardProfileRegistration';
import LoyaltyCardRegistration from './model/LoyaltyCardRegistration';
import LoyaltyDashboardData from './model/LoyaltyDashboardData';
import LoyaltyDashboardPointsBreakdown from './model/LoyaltyDashboardPointsBreakdown';
import LoyaltyLedger from './model/LoyaltyLedger';
import LoyaltyLedgerEntry from './model/LoyaltyLedgerEntry';
import LoyaltyLedgerTransactions from './model/LoyaltyLedgerTransactions';
import LoyaltyMembership from './model/LoyaltyMembership';
import LoyaltyProgram from './model/LoyaltyProgram';
import LoyaltyProgramBalance from './model/LoyaltyProgramBalance';
import LoyaltyProgramEntity from './model/LoyaltyProgramEntity';
import LoyaltyProgramLedgers from './model/LoyaltyProgramLedgers';
import LoyaltyProgramTransaction from './model/LoyaltyProgramTransaction';
import LoyaltyStatistics from './model/LoyaltyStatistics';
import LoyaltySubLedger from './model/LoyaltySubLedger';
import LoyaltyTier from './model/LoyaltyTier';
import ManagementKey from './model/ManagementKey';
import ManagerConfig from './model/ManagerConfig';
import Meta from './model/Meta';
import ModelExport from './model/ModelExport';
import ModelImport from './model/ModelImport';
import ModelReturn from './model/ModelReturn';
import MultiApplicationEntity from './model/MultiApplicationEntity';
import MultipleAttribute from './model/MultipleAttribute';
import MultipleAudiences from './model/MultipleAudiences';
import MultipleAudiencesItem from './model/MultipleAudiencesItem';
import MultipleCustomerProfileIntegrationRequest from './model/MultipleCustomerProfileIntegrationRequest';
import MultipleCustomerProfileIntegrationRequestItem from './model/MultipleCustomerProfileIntegrationRequestItem';
import MultipleCustomerProfileIntegrationResponseV2 from './model/MultipleCustomerProfileIntegrationResponseV2';
import MultipleNewAttribute from './model/MultipleNewAttribute';
import MultipleNewAudiences from './model/MultipleNewAudiences';
import MutableEntity from './model/MutableEntity';
import NewAccount from './model/NewAccount';
import NewAccountSignUp from './model/NewAccountSignUp';
import NewAdditionalCost from './model/NewAdditionalCost';
import NewApplication from './model/NewApplication';
import NewApplicationAPIKey from './model/NewApplicationAPIKey';
import NewAttribute from './model/NewAttribute';
import NewAudience from './model/NewAudience';
import NewBaseNotification from './model/NewBaseNotification';
import NewCampaign from './model/NewCampaign';
import NewCampaignCollection from './model/NewCampaignCollection';
import NewCampaignGroup from './model/NewCampaignGroup';
import NewCampaignSet from './model/NewCampaignSet';
import NewCampaignSetV2 from './model/NewCampaignSetV2';
import NewCampaignTemplate from './model/NewCampaignTemplate';
import NewCatalog from './model/NewCatalog';
import NewCollection from './model/NewCollection';
import NewCouponCreationJob from './model/NewCouponCreationJob';
import NewCoupons from './model/NewCoupons';
import NewCouponsForMultipleRecipients from './model/NewCouponsForMultipleRecipients';
import NewCustomEffect from './model/NewCustomEffect';
import NewCustomerProfile from './model/NewCustomerProfile';
import NewCustomerSession from './model/NewCustomerSession';
import NewCustomerSessionV2 from './model/NewCustomerSessionV2';
import NewEvent from './model/NewEvent';
import NewEventType from './model/NewEventType';
import NewGiveawaysPool from './model/NewGiveawaysPool';
import NewInternalAudience from './model/NewInternalAudience';
import NewInvitation from './model/NewInvitation';
import NewInviteEmail from './model/NewInviteEmail';
import NewLoyaltyProgram from './model/NewLoyaltyProgram';
import NewLoyaltyTier from './model/NewLoyaltyTier';
import NewManagementKey from './model/NewManagementKey';
import NewMultipleAudiencesItem from './model/NewMultipleAudiencesItem';
import NewNotificationWebhook from './model/NewNotificationWebhook';
import NewPassword from './model/NewPassword';
import NewPasswordEmail from './model/NewPasswordEmail';
import NewPicklist from './model/NewPicklist';
import NewReferral from './model/NewReferral';
import NewReferralsForMultipleAdvocates from './model/NewReferralsForMultipleAdvocates';
import NewReturn from './model/NewReturn';
import NewRole from './model/NewRole';
import NewRuleset from './model/NewRuleset';
import NewSamlConnection from './model/NewSamlConnection';
import NewTemplateDef from './model/NewTemplateDef';
import NewUser from './model/NewUser';
import NewWebhook from './model/NewWebhook';
import Notification from './model/Notification';
import NotificationWebhook from './model/NotificationWebhook';
import OutgoingIntegrationBrazePolicy from './model/OutgoingIntegrationBrazePolicy';
import OutgoingIntegrationConfiguration from './model/OutgoingIntegrationConfiguration';
import OutgoingIntegrationType from './model/OutgoingIntegrationType';
import OutgoingIntegrationTypes from './model/OutgoingIntegrationTypes';
import OutgoingIntegrationWebhookTemplate from './model/OutgoingIntegrationWebhookTemplate';
import OutgoingIntegrationWebhookTemplates from './model/OutgoingIntegrationWebhookTemplates';
import PatchItemCatalogAction from './model/PatchItemCatalogAction';
import PatchManyItemsCatalogAction from './model/PatchManyItemsCatalogAction';
import Picklist from './model/Picklist';
import PriorityPosition from './model/PriorityPosition';
import ProfileAudiencesChanges from './model/ProfileAudiencesChanges';
import RedeemReferralEffectProps from './model/RedeemReferralEffectProps';
import Referral from './model/Referral';
import ReferralConstraints from './model/ReferralConstraints';
import ReferralCreatedEffectProps from './model/ReferralCreatedEffectProps';
import ReferralRejectionReason from './model/ReferralRejectionReason';
import RejectCouponEffectProps from './model/RejectCouponEffectProps';
import RejectReferralEffectProps from './model/RejectReferralEffectProps';
import RemoveItemCatalogAction from './model/RemoveItemCatalogAction';
import RemoveManyItemsCatalogAction from './model/RemoveManyItemsCatalogAction';
import ReserveCouponEffectProps from './model/ReserveCouponEffectProps';
import ReturnIntegrationRequest from './model/ReturnIntegrationRequest';
import ReturnedCartItem from './model/ReturnedCartItem';
import Role from './model/Role';
import RoleAssign from './model/RoleAssign';
import RoleMembership from './model/RoleMembership';
import RoleV2 from './model/RoleV2';
import RoleV2ApplicationDetails from './model/RoleV2ApplicationDetails';
import RoleV2PermissionSet from './model/RoleV2PermissionSet';
import RoleV2Permissions from './model/RoleV2Permissions';
import RoleV2PermissionsRoles from './model/RoleV2PermissionsRoles';
import RollbackAddedLoyaltyPointsEffectProps from './model/RollbackAddedLoyaltyPointsEffectProps';
import RollbackCouponEffectProps from './model/RollbackCouponEffectProps';
import RollbackDeductedLoyaltyPointsEffectProps from './model/RollbackDeductedLoyaltyPointsEffectProps';
import RollbackDiscountEffectProps from './model/RollbackDiscountEffectProps';
import RollbackReferralEffectProps from './model/RollbackReferralEffectProps';
import Rule from './model/Rule';
import RuleFailureReason from './model/RuleFailureReason';
import Ruleset from './model/Ruleset';
import SamlConnection from './model/SamlConnection';
import SamlConnectionMetadata from './model/SamlConnectionMetadata';
import SamlLoginEndpoint from './model/SamlLoginEndpoint';
import Session from './model/Session';
import SetDiscountEffectProps from './model/SetDiscountEffectProps';
import SetDiscountPerAdditionalCostEffectProps from './model/SetDiscountPerAdditionalCostEffectProps';
import SetDiscountPerAdditionalCostPerItemEffectProps from './model/SetDiscountPerAdditionalCostPerItemEffectProps';
import SetDiscountPerItemEffectProps from './model/SetDiscountPerItemEffectProps';
import ShowBundleMetadataEffectProps from './model/ShowBundleMetadataEffectProps';
import ShowNotificationEffectProps from './model/ShowNotificationEffectProps';
import SlotDef from './model/SlotDef';
import StrikethroughChangedItem from './model/StrikethroughChangedItem';
import StrikethroughEffect from './model/StrikethroughEffect';
import StrikethroughLabelingNotification from './model/StrikethroughLabelingNotification';
import StrikethroughSetDiscountPerItemEffectProps from './model/StrikethroughSetDiscountPerItemEffectProps';
import StrikethroughTrigger from './model/StrikethroughTrigger';
import TalangAttribute from './model/TalangAttribute';
import TalangAttributeVisibility from './model/TalangAttributeVisibility';
import TemplateArgDef from './model/TemplateArgDef';
import TemplateDef from './model/TemplateDef';
import TemplateLimitConfig from './model/TemplateLimitConfig';
import Tier from './model/Tier';
import TransferLoyaltyCard from './model/TransferLoyaltyCard';
import TriggerWebhookEffectProps from './model/TriggerWebhookEffectProps';
import UpdateAccount from './model/UpdateAccount';
import UpdateApplication from './model/UpdateApplication';
import UpdateAttributeEffectProps from './model/UpdateAttributeEffectProps';
import UpdateAudience from './model/UpdateAudience';
import UpdateCampaign from './model/UpdateCampaign';
import UpdateCampaignCollection from './model/UpdateCampaignCollection';
import UpdateCampaignGroup from './model/UpdateCampaignGroup';
import UpdateCampaignTemplate from './model/UpdateCampaignTemplate';
import UpdateCatalog from './model/UpdateCatalog';
import UpdateCollection from './model/UpdateCollection';
import UpdateCoupon from './model/UpdateCoupon';
import UpdateCouponBatch from './model/UpdateCouponBatch';
import UpdateCustomEffect from './model/UpdateCustomEffect';
import UpdateLoyaltyCard from './model/UpdateLoyaltyCard';
import UpdateLoyaltyProgram from './model/UpdateLoyaltyProgram';
import UpdatePicklist from './model/UpdatePicklist';
import UpdateReferral from './model/UpdateReferral';
import UpdateReferralBatch from './model/UpdateReferralBatch';
import UpdateRole from './model/UpdateRole';
import UpdateUser from './model/UpdateUser';
import UpdateUserLatestFeedTimestamp from './model/UpdateUserLatestFeedTimestamp';
import User from './model/User';
import UserEntity from './model/UserEntity';
import UserFeedNotifications from './model/UserFeedNotifications';
import Webhook from './model/Webhook';
import WebhookActivationLogEntry from './model/WebhookActivationLogEntry';
import WebhookLogEntry from './model/WebhookLogEntry';
import WillAwardGiveawayEffectProps from './model/WillAwardGiveawayEffectProps';
import IntegrationApi from './api/IntegrationApi';
import ManagementApi from './api/ManagementApi';


/**
* Talon.One API SDK for Javascript.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TalonOne = require('index'); // See note below*.
* var xxxSvc = new TalonOne.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TalonOne.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TalonOne.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TalonOne.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 5.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The APIError model constructor.
     * @property {module:model/APIError}
     */
    APIError,

    /**
     * The AcceptCouponEffectProps model constructor.
     * @property {module:model/AcceptCouponEffectProps}
     */
    AcceptCouponEffectProps,

    /**
     * The AcceptReferralEffectProps model constructor.
     * @property {module:model/AcceptReferralEffectProps}
     */
    AcceptReferralEffectProps,

    /**
     * The AccessLogEntry model constructor.
     * @property {module:model/AccessLogEntry}
     */
    AccessLogEntry,

    /**
     * The Account model constructor.
     * @property {module:model/Account}
     */
    Account,

    /**
     * The AccountAdditionalCost model constructor.
     * @property {module:model/AccountAdditionalCost}
     */
    AccountAdditionalCost,

    /**
     * The AccountAnalytics model constructor.
     * @property {module:model/AccountAnalytics}
     */
    AccountAnalytics,

    /**
     * The AccountDashboardStatistic model constructor.
     * @property {module:model/AccountDashboardStatistic}
     */
    AccountDashboardStatistic,

    /**
     * The AccountDashboardStatisticApiCalls model constructor.
     * @property {module:model/AccountDashboardStatisticApiCalls}
     */
    AccountDashboardStatisticApiCalls,

    /**
     * The AccountDashboardStatisticCampaigns model constructor.
     * @property {module:model/AccountDashboardStatisticCampaigns}
     */
    AccountDashboardStatisticCampaigns,

    /**
     * The AccountDashboardStatisticDiscount model constructor.
     * @property {module:model/AccountDashboardStatisticDiscount}
     */
    AccountDashboardStatisticDiscount,

    /**
     * The AccountDashboardStatisticLoyaltyPoints model constructor.
     * @property {module:model/AccountDashboardStatisticLoyaltyPoints}
     */
    AccountDashboardStatisticLoyaltyPoints,

    /**
     * The AccountDashboardStatisticReferrals model constructor.
     * @property {module:model/AccountDashboardStatisticReferrals}
     */
    AccountDashboardStatisticReferrals,

    /**
     * The AccountDashboardStatisticRevenue model constructor.
     * @property {module:model/AccountDashboardStatisticRevenue}
     */
    AccountDashboardStatisticRevenue,

    /**
     * The AccountEntity model constructor.
     * @property {module:model/AccountEntity}
     */
    AccountEntity,

    /**
     * The AccountLimits model constructor.
     * @property {module:model/AccountLimits}
     */
    AccountLimits,

    /**
     * The AddFreeItemEffectProps model constructor.
     * @property {module:model/AddFreeItemEffectProps}
     */
    AddFreeItemEffectProps,

    /**
     * The AddItemCatalogAction model constructor.
     * @property {module:model/AddItemCatalogAction}
     */
    AddItemCatalogAction,

    /**
     * The AddLoyaltyPoints model constructor.
     * @property {module:model/AddLoyaltyPoints}
     */
    AddLoyaltyPoints,

    /**
     * The AddLoyaltyPointsEffectProps model constructor.
     * @property {module:model/AddLoyaltyPointsEffectProps}
     */
    AddLoyaltyPointsEffectProps,

    /**
     * The AddedDeductedPointsNotificationPolicy model constructor.
     * @property {module:model/AddedDeductedPointsNotificationPolicy}
     */
    AddedDeductedPointsNotificationPolicy,

    /**
     * The AdditionalCost model constructor.
     * @property {module:model/AdditionalCost}
     */
    AdditionalCost,

    /**
     * The Application model constructor.
     * @property {module:model/Application}
     */
    Application,

    /**
     * The ApplicationAPIKey model constructor.
     * @property {module:model/ApplicationAPIKey}
     */
    ApplicationAPIKey,

    /**
     * The ApplicationApiHealth model constructor.
     * @property {module:model/ApplicationApiHealth}
     */
    ApplicationApiHealth,

    /**
     * The ApplicationCampaignStats model constructor.
     * @property {module:model/ApplicationCampaignStats}
     */
    ApplicationCampaignStats,

    /**
     * The ApplicationCustomer model constructor.
     * @property {module:model/ApplicationCustomer}
     */
    ApplicationCustomer,

    /**
     * The ApplicationCustomerEntity model constructor.
     * @property {module:model/ApplicationCustomerEntity}
     */
    ApplicationCustomerEntity,

    /**
     * The ApplicationEntity model constructor.
     * @property {module:model/ApplicationEntity}
     */
    ApplicationEntity,

    /**
     * The ApplicationEvent model constructor.
     * @property {module:model/ApplicationEvent}
     */
    ApplicationEvent,

    /**
     * The ApplicationNotification model constructor.
     * @property {module:model/ApplicationNotification}
     */
    ApplicationNotification,

    /**
     * The ApplicationReferee model constructor.
     * @property {module:model/ApplicationReferee}
     */
    ApplicationReferee,

    /**
     * The ApplicationSession model constructor.
     * @property {module:model/ApplicationSession}
     */
    ApplicationSession,

    /**
     * The ApplicationSessionEntity model constructor.
     * @property {module:model/ApplicationSessionEntity}
     */
    ApplicationSessionEntity,

    /**
     * The AsyncCouponCreationResponse model constructor.
     * @property {module:model/AsyncCouponCreationResponse}
     */
    AsyncCouponCreationResponse,

    /**
     * The Attribute model constructor.
     * @property {module:model/Attribute}
     */
    Attribute,

    /**
     * The AttributesMandatory model constructor.
     * @property {module:model/AttributesMandatory}
     */
    AttributesMandatory,

    /**
     * The AttributesSettings model constructor.
     * @property {module:model/AttributesSettings}
     */
    AttributesSettings,

    /**
     * The Audience model constructor.
     * @property {module:model/Audience}
     */
    Audience,

    /**
     * The AudienceAnalytics model constructor.
     * @property {module:model/AudienceAnalytics}
     */
    AudienceAnalytics,

    /**
     * The AudienceCustomer model constructor.
     * @property {module:model/AudienceCustomer}
     */
    AudienceCustomer,

    /**
     * The AudienceIntegrationID model constructor.
     * @property {module:model/AudienceIntegrationID}
     */
    AudienceIntegrationID,

    /**
     * The AudienceMembership model constructor.
     * @property {module:model/AudienceMembership}
     */
    AudienceMembership,

    /**
     * The AwardGiveawayEffectProps model constructor.
     * @property {module:model/AwardGiveawayEffectProps}
     */
    AwardGiveawayEffectProps,

    /**
     * The BaseLoyaltyProgram model constructor.
     * @property {module:model/BaseLoyaltyProgram}
     */
    BaseLoyaltyProgram,

    /**
     * The BaseNotification model constructor.
     * @property {module:model/BaseNotification}
     */
    BaseNotification,

    /**
     * The BaseNotificationEntity model constructor.
     * @property {module:model/BaseNotificationEntity}
     */
    BaseNotificationEntity,

    /**
     * The BaseNotificationWebhook model constructor.
     * @property {module:model/BaseNotificationWebhook}
     */
    BaseNotificationWebhook,

    /**
     * The BaseNotifications model constructor.
     * @property {module:model/BaseNotifications}
     */
    BaseNotifications,

    /**
     * The BaseSamlConnection model constructor.
     * @property {module:model/BaseSamlConnection}
     */
    BaseSamlConnection,

    /**
     * The Binding model constructor.
     * @property {module:model/Binding}
     */
    Binding,

    /**
     * The BulkApplicationNotification model constructor.
     * @property {module:model/BulkApplicationNotification}
     */
    BulkApplicationNotification,

    /**
     * The BulkCampaignNotification model constructor.
     * @property {module:model/BulkCampaignNotification}
     */
    BulkCampaignNotification,

    /**
     * The Campaign model constructor.
     * @property {module:model/Campaign}
     */
    Campaign,

    /**
     * The CampaignActivationRequest model constructor.
     * @property {module:model/CampaignActivationRequest}
     */
    CampaignActivationRequest,

    /**
     * The CampaignAnalytics model constructor.
     * @property {module:model/CampaignAnalytics}
     */
    CampaignAnalytics,

    /**
     * The CampaignCollection model constructor.
     * @property {module:model/CampaignCollection}
     */
    CampaignCollection,

    /**
     * The CampaignCollectionWithoutPayload model constructor.
     * @property {module:model/CampaignCollectionWithoutPayload}
     */
    CampaignCollectionWithoutPayload,

    /**
     * The CampaignCopy model constructor.
     * @property {module:model/CampaignCopy}
     */
    CampaignCopy,

    /**
     * The CampaignCreatedNotification model constructor.
     * @property {module:model/CampaignCreatedNotification}
     */
    CampaignCreatedNotification,

    /**
     * The CampaignDeletedNotification model constructor.
     * @property {module:model/CampaignDeletedNotification}
     */
    CampaignDeletedNotification,

    /**
     * The CampaignEditedNotification model constructor.
     * @property {module:model/CampaignEditedNotification}
     */
    CampaignEditedNotification,

    /**
     * The CampaignEntity model constructor.
     * @property {module:model/CampaignEntity}
     */
    CampaignEntity,

    /**
     * The CampaignGroup model constructor.
     * @property {module:model/CampaignGroup}
     */
    CampaignGroup,

    /**
     * The CampaignGroupEntity model constructor.
     * @property {module:model/CampaignGroupEntity}
     */
    CampaignGroupEntity,

    /**
     * The CampaignNotification model constructor.
     * @property {module:model/CampaignNotification}
     */
    CampaignNotification,

    /**
     * The CampaignPrioritiesChangedNotification model constructor.
     * @property {module:model/CampaignPrioritiesChangedNotification}
     */
    CampaignPrioritiesChangedNotification,

    /**
     * The CampaignPrioritiesV2 model constructor.
     * @property {module:model/CampaignPrioritiesV2}
     */
    CampaignPrioritiesV2,

    /**
     * The CampaignRulesetChangedNotification model constructor.
     * @property {module:model/CampaignRulesetChangedNotification}
     */
    CampaignRulesetChangedNotification,

    /**
     * The CampaignSearch model constructor.
     * @property {module:model/CampaignSearch}
     */
    CampaignSearch,

    /**
     * The CampaignSet model constructor.
     * @property {module:model/CampaignSet}
     */
    CampaignSet,

    /**
     * The CampaignSetBranchNode model constructor.
     * @property {module:model/CampaignSetBranchNode}
     */
    CampaignSetBranchNode,

    /**
     * The CampaignSetIDs model constructor.
     * @property {module:model/CampaignSetIDs}
     */
    CampaignSetIDs,

    /**
     * The CampaignSetLeafNode model constructor.
     * @property {module:model/CampaignSetLeafNode}
     */
    CampaignSetLeafNode,

    /**
     * The CampaignSetNode model constructor.
     * @property {module:model/CampaignSetNode}
     */
    CampaignSetNode,

    /**
     * The CampaignSetV2 model constructor.
     * @property {module:model/CampaignSetV2}
     */
    CampaignSetV2,

    /**
     * The CampaignStateChangedNotification model constructor.
     * @property {module:model/CampaignStateChangedNotification}
     */
    CampaignStateChangedNotification,

    /**
     * The CampaignTemplate model constructor.
     * @property {module:model/CampaignTemplate}
     */
    CampaignTemplate,

    /**
     * The CampaignTemplateCollection model constructor.
     * @property {module:model/CampaignTemplateCollection}
     */
    CampaignTemplateCollection,

    /**
     * The CampaignTemplateParams model constructor.
     * @property {module:model/CampaignTemplateParams}
     */
    CampaignTemplateParams,

    /**
     * The CardLedgerTransactionLogEntry model constructor.
     * @property {module:model/CardLedgerTransactionLogEntry}
     */
    CardLedgerTransactionLogEntry,

    /**
     * The CardLedgerTransactionLogEntryIntegrationAPI model constructor.
     * @property {module:model/CardLedgerTransactionLogEntryIntegrationAPI}
     */
    CardLedgerTransactionLogEntryIntegrationAPI,

    /**
     * The CartItem model constructor.
     * @property {module:model/CartItem}
     */
    CartItem,

    /**
     * The Catalog model constructor.
     * @property {module:model/Catalog}
     */
    Catalog,

    /**
     * The CatalogAction model constructor.
     * @property {module:model/CatalogAction}
     */
    CatalogAction,

    /**
     * The CatalogActionFilter model constructor.
     * @property {module:model/CatalogActionFilter}
     */
    CatalogActionFilter,

    /**
     * The CatalogItem model constructor.
     * @property {module:model/CatalogItem}
     */
    CatalogItem,

    /**
     * The CatalogSyncRequest model constructor.
     * @property {module:model/CatalogSyncRequest}
     */
    CatalogSyncRequest,

    /**
     * The CatalogsStrikethroughNotificationPolicy model constructor.
     * @property {module:model/CatalogsStrikethroughNotificationPolicy}
     */
    CatalogsStrikethroughNotificationPolicy,

    /**
     * The Change model constructor.
     * @property {module:model/Change}
     */
    Change,

    /**
     * The ChangeProfilePassword model constructor.
     * @property {module:model/ChangeProfilePassword}
     */
    ChangeProfilePassword,

    /**
     * The CodeGeneratorSettings model constructor.
     * @property {module:model/CodeGeneratorSettings}
     */
    CodeGeneratorSettings,

    /**
     * The Collection model constructor.
     * @property {module:model/Collection}
     */
    Collection,

    /**
     * The CollectionItem model constructor.
     * @property {module:model/CollectionItem}
     */
    CollectionItem,

    /**
     * The CollectionWithoutPayload model constructor.
     * @property {module:model/CollectionWithoutPayload}
     */
    CollectionWithoutPayload,

    /**
     * The Coupon model constructor.
     * @property {module:model/Coupon}
     */
    Coupon,

    /**
     * The CouponConstraints model constructor.
     * @property {module:model/CouponConstraints}
     */
    CouponConstraints,

    /**
     * The CouponCreatedEffectProps model constructor.
     * @property {module:model/CouponCreatedEffectProps}
     */
    CouponCreatedEffectProps,

    /**
     * The CouponCreationJob model constructor.
     * @property {module:model/CouponCreationJob}
     */
    CouponCreationJob,

    /**
     * The CouponLimitConfigs model constructor.
     * @property {module:model/CouponLimitConfigs}
     */
    CouponLimitConfigs,

    /**
     * The CouponRejectionReason model constructor.
     * @property {module:model/CouponRejectionReason}
     */
    CouponRejectionReason,

    /**
     * The CouponReservations model constructor.
     * @property {module:model/CouponReservations}
     */
    CouponReservations,

    /**
     * The CouponSearch model constructor.
     * @property {module:model/CouponSearch}
     */
    CouponSearch,

    /**
     * The CouponValue model constructor.
     * @property {module:model/CouponValue}
     */
    CouponValue,

    /**
     * The CouponsNotificationPolicy model constructor.
     * @property {module:model/CouponsNotificationPolicy}
     */
    CouponsNotificationPolicy,

    /**
     * The CreateApplicationAPIKey model constructor.
     * @property {module:model/CreateApplicationAPIKey}
     */
    CreateApplicationAPIKey,

    /**
     * The CreateManagementKey model constructor.
     * @property {module:model/CreateManagementKey}
     */
    CreateManagementKey,

    /**
     * The CreateTemplateCampaign model constructor.
     * @property {module:model/CreateTemplateCampaign}
     */
    CreateTemplateCampaign,

    /**
     * The CreateTemplateCampaignResponse model constructor.
     * @property {module:model/CreateTemplateCampaignResponse}
     */
    CreateTemplateCampaignResponse,

    /**
     * The CustomEffect model constructor.
     * @property {module:model/CustomEffect}
     */
    CustomEffect,

    /**
     * The CustomEffectProps model constructor.
     * @property {module:model/CustomEffectProps}
     */
    CustomEffectProps,

    /**
     * The CustomerActivityReport model constructor.
     * @property {module:model/CustomerActivityReport}
     */
    CustomerActivityReport,

    /**
     * The CustomerAnalytics model constructor.
     * @property {module:model/CustomerAnalytics}
     */
    CustomerAnalytics,

    /**
     * The CustomerInventory model constructor.
     * @property {module:model/CustomerInventory}
     */
    CustomerInventory,

    /**
     * The CustomerProfile model constructor.
     * @property {module:model/CustomerProfile}
     */
    CustomerProfile,

    /**
     * The CustomerProfileAudienceRequest model constructor.
     * @property {module:model/CustomerProfileAudienceRequest}
     */
    CustomerProfileAudienceRequest,

    /**
     * The CustomerProfileAudienceRequestItem model constructor.
     * @property {module:model/CustomerProfileAudienceRequestItem}
     */
    CustomerProfileAudienceRequestItem,

    /**
     * The CustomerProfileIntegrationRequestV2 model constructor.
     * @property {module:model/CustomerProfileIntegrationRequestV2}
     */
    CustomerProfileIntegrationRequestV2,

    /**
     * The CustomerProfileSearchQuery model constructor.
     * @property {module:model/CustomerProfileSearchQuery}
     */
    CustomerProfileSearchQuery,

    /**
     * The CustomerProfileUpdateV2Response model constructor.
     * @property {module:model/CustomerProfileUpdateV2Response}
     */
    CustomerProfileUpdateV2Response,

    /**
     * The CustomerSession model constructor.
     * @property {module:model/CustomerSession}
     */
    CustomerSession,

    /**
     * The CustomerSessionV2 model constructor.
     * @property {module:model/CustomerSessionV2}
     */
    CustomerSessionV2,

    /**
     * The DeductLoyaltyPoints model constructor.
     * @property {module:model/DeductLoyaltyPoints}
     */
    DeductLoyaltyPoints,

    /**
     * The DeductLoyaltyPointsEffectProps model constructor.
     * @property {module:model/DeductLoyaltyPointsEffectProps}
     */
    DeductLoyaltyPointsEffectProps,

    /**
     * The Effect model constructor.
     * @property {module:model/Effect}
     */
    Effect,

    /**
     * The EffectEntity model constructor.
     * @property {module:model/EffectEntity}
     */
    EffectEntity,

    /**
     * The EmailEntity model constructor.
     * @property {module:model/EmailEntity}
     */
    EmailEntity,

    /**
     * The Endpoint model constructor.
     * @property {module:model/Endpoint}
     */
    Endpoint,

    /**
     * The Entity model constructor.
     * @property {module:model/Entity}
     */
    Entity,

    /**
     * The EntityWithTalangVisibleID model constructor.
     * @property {module:model/EntityWithTalangVisibleID}
     */
    EntityWithTalangVisibleID,

    /**
     * The Environment model constructor.
     * @property {module:model/Environment}
     */
    Environment,

    /**
     * The ErrorEffectProps model constructor.
     * @property {module:model/ErrorEffectProps}
     */
    ErrorEffectProps,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The ErrorResponseWithStatus model constructor.
     * @property {module:model/ErrorResponseWithStatus}
     */
    ErrorResponseWithStatus,

    /**
     * The ErrorSource model constructor.
     * @property {module:model/ErrorSource}
     */
    ErrorSource,

    /**
     * The EvaluableCampaignIds model constructor.
     * @property {module:model/EvaluableCampaignIds}
     */
    EvaluableCampaignIds,

    /**
     * The Event model constructor.
     * @property {module:model/Event}
     */
    Event,

    /**
     * The EventType model constructor.
     * @property {module:model/EventType}
     */
    EventType,

    /**
     * The EventV2 model constructor.
     * @property {module:model/EventV2}
     */
    EventV2,

    /**
     * The ExpiringPointsNotificationPolicy model constructor.
     * @property {module:model/ExpiringPointsNotificationPolicy}
     */
    ExpiringPointsNotificationPolicy,

    /**
     * The ExpiringPointsNotificationTrigger model constructor.
     * @property {module:model/ExpiringPointsNotificationTrigger}
     */
    ExpiringPointsNotificationTrigger,

    /**
     * The FeatureFlag model constructor.
     * @property {module:model/FeatureFlag}
     */
    FeatureFlag,

    /**
     * The FeaturesFeed model constructor.
     * @property {module:model/FeaturesFeed}
     */
    FeaturesFeed,

    /**
     * The FeedNotification model constructor.
     * @property {module:model/FeedNotification}
     */
    FeedNotification,

    /**
     * The FrontendState model constructor.
     * @property {module:model/FrontendState}
     */
    FrontendState,

    /**
     * The FuncArgDef model constructor.
     * @property {module:model/FuncArgDef}
     */
    FuncArgDef,

    /**
     * The FunctionDef model constructor.
     * @property {module:model/FunctionDef}
     */
    FunctionDef,

    /**
     * The Giveaway model constructor.
     * @property {module:model/Giveaway}
     */
    Giveaway,

    /**
     * The GiveawaysPool model constructor.
     * @property {module:model/GiveawaysPool}
     */
    GiveawaysPool,

    /**
     * The ImportEntity model constructor.
     * @property {module:model/ImportEntity}
     */
    ImportEntity,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse20010 model constructor.
     * @property {module:model/InlineResponse20010}
     */
    InlineResponse20010,

    /**
     * The InlineResponse20011 model constructor.
     * @property {module:model/InlineResponse20011}
     */
    InlineResponse20011,

    /**
     * The InlineResponse20012 model constructor.
     * @property {module:model/InlineResponse20012}
     */
    InlineResponse20012,

    /**
     * The InlineResponse20013 model constructor.
     * @property {module:model/InlineResponse20013}
     */
    InlineResponse20013,

    /**
     * The InlineResponse20014 model constructor.
     * @property {module:model/InlineResponse20014}
     */
    InlineResponse20014,

    /**
     * The InlineResponse20015 model constructor.
     * @property {module:model/InlineResponse20015}
     */
    InlineResponse20015,

    /**
     * The InlineResponse20016 model constructor.
     * @property {module:model/InlineResponse20016}
     */
    InlineResponse20016,

    /**
     * The InlineResponse20017 model constructor.
     * @property {module:model/InlineResponse20017}
     */
    InlineResponse20017,

    /**
     * The InlineResponse20018 model constructor.
     * @property {module:model/InlineResponse20018}
     */
    InlineResponse20018,

    /**
     * The InlineResponse20019 model constructor.
     * @property {module:model/InlineResponse20019}
     */
    InlineResponse20019,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse20020 model constructor.
     * @property {module:model/InlineResponse20020}
     */
    InlineResponse20020,

    /**
     * The InlineResponse20021 model constructor.
     * @property {module:model/InlineResponse20021}
     */
    InlineResponse20021,

    /**
     * The InlineResponse20022 model constructor.
     * @property {module:model/InlineResponse20022}
     */
    InlineResponse20022,

    /**
     * The InlineResponse20023 model constructor.
     * @property {module:model/InlineResponse20023}
     */
    InlineResponse20023,

    /**
     * The InlineResponse20024 model constructor.
     * @property {module:model/InlineResponse20024}
     */
    InlineResponse20024,

    /**
     * The InlineResponse20025 model constructor.
     * @property {module:model/InlineResponse20025}
     */
    InlineResponse20025,

    /**
     * The InlineResponse20026 model constructor.
     * @property {module:model/InlineResponse20026}
     */
    InlineResponse20026,

    /**
     * The InlineResponse20027 model constructor.
     * @property {module:model/InlineResponse20027}
     */
    InlineResponse20027,

    /**
     * The InlineResponse20028 model constructor.
     * @property {module:model/InlineResponse20028}
     */
    InlineResponse20028,

    /**
     * The InlineResponse20029 model constructor.
     * @property {module:model/InlineResponse20029}
     */
    InlineResponse20029,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse20030 model constructor.
     * @property {module:model/InlineResponse20030}
     */
    InlineResponse20030,

    /**
     * The InlineResponse20031 model constructor.
     * @property {module:model/InlineResponse20031}
     */
    InlineResponse20031,

    /**
     * The InlineResponse20032 model constructor.
     * @property {module:model/InlineResponse20032}
     */
    InlineResponse20032,

    /**
     * The InlineResponse20033 model constructor.
     * @property {module:model/InlineResponse20033}
     */
    InlineResponse20033,

    /**
     * The InlineResponse20034 model constructor.
     * @property {module:model/InlineResponse20034}
     */
    InlineResponse20034,

    /**
     * The InlineResponse20035 model constructor.
     * @property {module:model/InlineResponse20035}
     */
    InlineResponse20035,

    /**
     * The InlineResponse20036 model constructor.
     * @property {module:model/InlineResponse20036}
     */
    InlineResponse20036,

    /**
     * The InlineResponse20037 model constructor.
     * @property {module:model/InlineResponse20037}
     */
    InlineResponse20037,

    /**
     * The InlineResponse20038 model constructor.
     * @property {module:model/InlineResponse20038}
     */
    InlineResponse20038,

    /**
     * The InlineResponse20039 model constructor.
     * @property {module:model/InlineResponse20039}
     */
    InlineResponse20039,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse2006 model constructor.
     * @property {module:model/InlineResponse2006}
     */
    InlineResponse2006,

    /**
     * The InlineResponse2007 model constructor.
     * @property {module:model/InlineResponse2007}
     */
    InlineResponse2007,

    /**
     * The InlineResponse2008 model constructor.
     * @property {module:model/InlineResponse2008}
     */
    InlineResponse2008,

    /**
     * The InlineResponse2009 model constructor.
     * @property {module:model/InlineResponse2009}
     */
    InlineResponse2009,

    /**
     * The InlineResponse201 model constructor.
     * @property {module:model/InlineResponse201}
     */
    InlineResponse201,

    /**
     * The IntegrationCoupon model constructor.
     * @property {module:model/IntegrationCoupon}
     */
    IntegrationCoupon,

    /**
     * The IntegrationCustomerSessionResponse model constructor.
     * @property {module:model/IntegrationCustomerSessionResponse}
     */
    IntegrationCustomerSessionResponse,

    /**
     * The IntegrationEntity model constructor.
     * @property {module:model/IntegrationEntity}
     */
    IntegrationEntity,

    /**
     * The IntegrationEvent model constructor.
     * @property {module:model/IntegrationEvent}
     */
    IntegrationEvent,

    /**
     * The IntegrationEventV2Request model constructor.
     * @property {module:model/IntegrationEventV2Request}
     */
    IntegrationEventV2Request,

    /**
     * The IntegrationProfileEntity model constructor.
     * @property {module:model/IntegrationProfileEntity}
     */
    IntegrationProfileEntity,

    /**
     * The IntegrationRequest model constructor.
     * @property {module:model/IntegrationRequest}
     */
    IntegrationRequest,

    /**
     * The IntegrationState model constructor.
     * @property {module:model/IntegrationState}
     */
    IntegrationState,

    /**
     * The IntegrationStateV2 model constructor.
     * @property {module:model/IntegrationStateV2}
     */
    IntegrationStateV2,

    /**
     * The InventoryCoupon model constructor.
     * @property {module:model/InventoryCoupon}
     */
    InventoryCoupon,

    /**
     * The InventoryReferral model constructor.
     * @property {module:model/InventoryReferral}
     */
    InventoryReferral,

    /**
     * The ItemAttribute model constructor.
     * @property {module:model/ItemAttribute}
     */
    ItemAttribute,

    /**
     * The LedgerEntry model constructor.
     * @property {module:model/LedgerEntry}
     */
    LedgerEntry,

    /**
     * The LedgerInfo model constructor.
     * @property {module:model/LedgerInfo}
     */
    LedgerInfo,

    /**
     * The LedgerTransactionLogEntryIntegrationAPI model constructor.
     * @property {module:model/LedgerTransactionLogEntryIntegrationAPI}
     */
    LedgerTransactionLogEntryIntegrationAPI,

    /**
     * The LibraryAttribute model constructor.
     * @property {module:model/LibraryAttribute}
     */
    LibraryAttribute,

    /**
     * The LimitConfig model constructor.
     * @property {module:model/LimitConfig}
     */
    LimitConfig,

    /**
     * The LimitCounter model constructor.
     * @property {module:model/LimitCounter}
     */
    LimitCounter,

    /**
     * The LoginParams model constructor.
     * @property {module:model/LoginParams}
     */
    LoginParams,

    /**
     * The Loyalty model constructor.
     * @property {module:model/Loyalty}
     */
    Loyalty,

    /**
     * The LoyaltyBalance model constructor.
     * @property {module:model/LoyaltyBalance}
     */
    LoyaltyBalance,

    /**
     * The LoyaltyBalances model constructor.
     * @property {module:model/LoyaltyBalances}
     */
    LoyaltyBalances,

    /**
     * The LoyaltyCard model constructor.
     * @property {module:model/LoyaltyCard}
     */
    LoyaltyCard,

    /**
     * The LoyaltyCardProfileRegistration model constructor.
     * @property {module:model/LoyaltyCardProfileRegistration}
     */
    LoyaltyCardProfileRegistration,

    /**
     * The LoyaltyCardRegistration model constructor.
     * @property {module:model/LoyaltyCardRegistration}
     */
    LoyaltyCardRegistration,

    /**
     * The LoyaltyDashboardData model constructor.
     * @property {module:model/LoyaltyDashboardData}
     */
    LoyaltyDashboardData,

    /**
     * The LoyaltyDashboardPointsBreakdown model constructor.
     * @property {module:model/LoyaltyDashboardPointsBreakdown}
     */
    LoyaltyDashboardPointsBreakdown,

    /**
     * The LoyaltyLedger model constructor.
     * @property {module:model/LoyaltyLedger}
     */
    LoyaltyLedger,

    /**
     * The LoyaltyLedgerEntry model constructor.
     * @property {module:model/LoyaltyLedgerEntry}
     */
    LoyaltyLedgerEntry,

    /**
     * The LoyaltyLedgerTransactions model constructor.
     * @property {module:model/LoyaltyLedgerTransactions}
     */
    LoyaltyLedgerTransactions,

    /**
     * The LoyaltyMembership model constructor.
     * @property {module:model/LoyaltyMembership}
     */
    LoyaltyMembership,

    /**
     * The LoyaltyProgram model constructor.
     * @property {module:model/LoyaltyProgram}
     */
    LoyaltyProgram,

    /**
     * The LoyaltyProgramBalance model constructor.
     * @property {module:model/LoyaltyProgramBalance}
     */
    LoyaltyProgramBalance,

    /**
     * The LoyaltyProgramEntity model constructor.
     * @property {module:model/LoyaltyProgramEntity}
     */
    LoyaltyProgramEntity,

    /**
     * The LoyaltyProgramLedgers model constructor.
     * @property {module:model/LoyaltyProgramLedgers}
     */
    LoyaltyProgramLedgers,

    /**
     * The LoyaltyProgramTransaction model constructor.
     * @property {module:model/LoyaltyProgramTransaction}
     */
    LoyaltyProgramTransaction,

    /**
     * The LoyaltyStatistics model constructor.
     * @property {module:model/LoyaltyStatistics}
     */
    LoyaltyStatistics,

    /**
     * The LoyaltySubLedger model constructor.
     * @property {module:model/LoyaltySubLedger}
     */
    LoyaltySubLedger,

    /**
     * The LoyaltyTier model constructor.
     * @property {module:model/LoyaltyTier}
     */
    LoyaltyTier,

    /**
     * The ManagementKey model constructor.
     * @property {module:model/ManagementKey}
     */
    ManagementKey,

    /**
     * The ManagerConfig model constructor.
     * @property {module:model/ManagerConfig}
     */
    ManagerConfig,

    /**
     * The Meta model constructor.
     * @property {module:model/Meta}
     */
    Meta,

    /**
     * The ModelExport model constructor.
     * @property {module:model/ModelExport}
     */
    ModelExport,

    /**
     * The ModelImport model constructor.
     * @property {module:model/ModelImport}
     */
    ModelImport,

    /**
     * The ModelReturn model constructor.
     * @property {module:model/ModelReturn}
     */
    ModelReturn,

    /**
     * The MultiApplicationEntity model constructor.
     * @property {module:model/MultiApplicationEntity}
     */
    MultiApplicationEntity,

    /**
     * The MultipleAttribute model constructor.
     * @property {module:model/MultipleAttribute}
     */
    MultipleAttribute,

    /**
     * The MultipleAudiences model constructor.
     * @property {module:model/MultipleAudiences}
     */
    MultipleAudiences,

    /**
     * The MultipleAudiencesItem model constructor.
     * @property {module:model/MultipleAudiencesItem}
     */
    MultipleAudiencesItem,

    /**
     * The MultipleCustomerProfileIntegrationRequest model constructor.
     * @property {module:model/MultipleCustomerProfileIntegrationRequest}
     */
    MultipleCustomerProfileIntegrationRequest,

    /**
     * The MultipleCustomerProfileIntegrationRequestItem model constructor.
     * @property {module:model/MultipleCustomerProfileIntegrationRequestItem}
     */
    MultipleCustomerProfileIntegrationRequestItem,

    /**
     * The MultipleCustomerProfileIntegrationResponseV2 model constructor.
     * @property {module:model/MultipleCustomerProfileIntegrationResponseV2}
     */
    MultipleCustomerProfileIntegrationResponseV2,

    /**
     * The MultipleNewAttribute model constructor.
     * @property {module:model/MultipleNewAttribute}
     */
    MultipleNewAttribute,

    /**
     * The MultipleNewAudiences model constructor.
     * @property {module:model/MultipleNewAudiences}
     */
    MultipleNewAudiences,

    /**
     * The MutableEntity model constructor.
     * @property {module:model/MutableEntity}
     */
    MutableEntity,

    /**
     * The NewAccount model constructor.
     * @property {module:model/NewAccount}
     */
    NewAccount,

    /**
     * The NewAccountSignUp model constructor.
     * @property {module:model/NewAccountSignUp}
     */
    NewAccountSignUp,

    /**
     * The NewAdditionalCost model constructor.
     * @property {module:model/NewAdditionalCost}
     */
    NewAdditionalCost,

    /**
     * The NewApplication model constructor.
     * @property {module:model/NewApplication}
     */
    NewApplication,

    /**
     * The NewApplicationAPIKey model constructor.
     * @property {module:model/NewApplicationAPIKey}
     */
    NewApplicationAPIKey,

    /**
     * The NewAttribute model constructor.
     * @property {module:model/NewAttribute}
     */
    NewAttribute,

    /**
     * The NewAudience model constructor.
     * @property {module:model/NewAudience}
     */
    NewAudience,

    /**
     * The NewBaseNotification model constructor.
     * @property {module:model/NewBaseNotification}
     */
    NewBaseNotification,

    /**
     * The NewCampaign model constructor.
     * @property {module:model/NewCampaign}
     */
    NewCampaign,

    /**
     * The NewCampaignCollection model constructor.
     * @property {module:model/NewCampaignCollection}
     */
    NewCampaignCollection,

    /**
     * The NewCampaignGroup model constructor.
     * @property {module:model/NewCampaignGroup}
     */
    NewCampaignGroup,

    /**
     * The NewCampaignSet model constructor.
     * @property {module:model/NewCampaignSet}
     */
    NewCampaignSet,

    /**
     * The NewCampaignSetV2 model constructor.
     * @property {module:model/NewCampaignSetV2}
     */
    NewCampaignSetV2,

    /**
     * The NewCampaignTemplate model constructor.
     * @property {module:model/NewCampaignTemplate}
     */
    NewCampaignTemplate,

    /**
     * The NewCatalog model constructor.
     * @property {module:model/NewCatalog}
     */
    NewCatalog,

    /**
     * The NewCollection model constructor.
     * @property {module:model/NewCollection}
     */
    NewCollection,

    /**
     * The NewCouponCreationJob model constructor.
     * @property {module:model/NewCouponCreationJob}
     */
    NewCouponCreationJob,

    /**
     * The NewCoupons model constructor.
     * @property {module:model/NewCoupons}
     */
    NewCoupons,

    /**
     * The NewCouponsForMultipleRecipients model constructor.
     * @property {module:model/NewCouponsForMultipleRecipients}
     */
    NewCouponsForMultipleRecipients,

    /**
     * The NewCustomEffect model constructor.
     * @property {module:model/NewCustomEffect}
     */
    NewCustomEffect,

    /**
     * The NewCustomerProfile model constructor.
     * @property {module:model/NewCustomerProfile}
     */
    NewCustomerProfile,

    /**
     * The NewCustomerSession model constructor.
     * @property {module:model/NewCustomerSession}
     */
    NewCustomerSession,

    /**
     * The NewCustomerSessionV2 model constructor.
     * @property {module:model/NewCustomerSessionV2}
     */
    NewCustomerSessionV2,

    /**
     * The NewEvent model constructor.
     * @property {module:model/NewEvent}
     */
    NewEvent,

    /**
     * The NewEventType model constructor.
     * @property {module:model/NewEventType}
     */
    NewEventType,

    /**
     * The NewGiveawaysPool model constructor.
     * @property {module:model/NewGiveawaysPool}
     */
    NewGiveawaysPool,

    /**
     * The NewInternalAudience model constructor.
     * @property {module:model/NewInternalAudience}
     */
    NewInternalAudience,

    /**
     * The NewInvitation model constructor.
     * @property {module:model/NewInvitation}
     */
    NewInvitation,

    /**
     * The NewInviteEmail model constructor.
     * @property {module:model/NewInviteEmail}
     */
    NewInviteEmail,

    /**
     * The NewLoyaltyProgram model constructor.
     * @property {module:model/NewLoyaltyProgram}
     */
    NewLoyaltyProgram,

    /**
     * The NewLoyaltyTier model constructor.
     * @property {module:model/NewLoyaltyTier}
     */
    NewLoyaltyTier,

    /**
     * The NewManagementKey model constructor.
     * @property {module:model/NewManagementKey}
     */
    NewManagementKey,

    /**
     * The NewMultipleAudiencesItem model constructor.
     * @property {module:model/NewMultipleAudiencesItem}
     */
    NewMultipleAudiencesItem,

    /**
     * The NewNotificationWebhook model constructor.
     * @property {module:model/NewNotificationWebhook}
     */
    NewNotificationWebhook,

    /**
     * The NewPassword model constructor.
     * @property {module:model/NewPassword}
     */
    NewPassword,

    /**
     * The NewPasswordEmail model constructor.
     * @property {module:model/NewPasswordEmail}
     */
    NewPasswordEmail,

    /**
     * The NewPicklist model constructor.
     * @property {module:model/NewPicklist}
     */
    NewPicklist,

    /**
     * The NewReferral model constructor.
     * @property {module:model/NewReferral}
     */
    NewReferral,

    /**
     * The NewReferralsForMultipleAdvocates model constructor.
     * @property {module:model/NewReferralsForMultipleAdvocates}
     */
    NewReferralsForMultipleAdvocates,

    /**
     * The NewReturn model constructor.
     * @property {module:model/NewReturn}
     */
    NewReturn,

    /**
     * The NewRole model constructor.
     * @property {module:model/NewRole}
     */
    NewRole,

    /**
     * The NewRuleset model constructor.
     * @property {module:model/NewRuleset}
     */
    NewRuleset,

    /**
     * The NewSamlConnection model constructor.
     * @property {module:model/NewSamlConnection}
     */
    NewSamlConnection,

    /**
     * The NewTemplateDef model constructor.
     * @property {module:model/NewTemplateDef}
     */
    NewTemplateDef,

    /**
     * The NewUser model constructor.
     * @property {module:model/NewUser}
     */
    NewUser,

    /**
     * The NewWebhook model constructor.
     * @property {module:model/NewWebhook}
     */
    NewWebhook,

    /**
     * The Notification model constructor.
     * @property {module:model/Notification}
     */
    Notification,

    /**
     * The NotificationWebhook model constructor.
     * @property {module:model/NotificationWebhook}
     */
    NotificationWebhook,

    /**
     * The OutgoingIntegrationBrazePolicy model constructor.
     * @property {module:model/OutgoingIntegrationBrazePolicy}
     */
    OutgoingIntegrationBrazePolicy,

    /**
     * The OutgoingIntegrationConfiguration model constructor.
     * @property {module:model/OutgoingIntegrationConfiguration}
     */
    OutgoingIntegrationConfiguration,

    /**
     * The OutgoingIntegrationType model constructor.
     * @property {module:model/OutgoingIntegrationType}
     */
    OutgoingIntegrationType,

    /**
     * The OutgoingIntegrationTypes model constructor.
     * @property {module:model/OutgoingIntegrationTypes}
     */
    OutgoingIntegrationTypes,

    /**
     * The OutgoingIntegrationWebhookTemplate model constructor.
     * @property {module:model/OutgoingIntegrationWebhookTemplate}
     */
    OutgoingIntegrationWebhookTemplate,

    /**
     * The OutgoingIntegrationWebhookTemplates model constructor.
     * @property {module:model/OutgoingIntegrationWebhookTemplates}
     */
    OutgoingIntegrationWebhookTemplates,

    /**
     * The PatchItemCatalogAction model constructor.
     * @property {module:model/PatchItemCatalogAction}
     */
    PatchItemCatalogAction,

    /**
     * The PatchManyItemsCatalogAction model constructor.
     * @property {module:model/PatchManyItemsCatalogAction}
     */
    PatchManyItemsCatalogAction,

    /**
     * The Picklist model constructor.
     * @property {module:model/Picklist}
     */
    Picklist,

    /**
     * The PriorityPosition model constructor.
     * @property {module:model/PriorityPosition}
     */
    PriorityPosition,

    /**
     * The ProfileAudiencesChanges model constructor.
     * @property {module:model/ProfileAudiencesChanges}
     */
    ProfileAudiencesChanges,

    /**
     * The RedeemReferralEffectProps model constructor.
     * @property {module:model/RedeemReferralEffectProps}
     */
    RedeemReferralEffectProps,

    /**
     * The Referral model constructor.
     * @property {module:model/Referral}
     */
    Referral,

    /**
     * The ReferralConstraints model constructor.
     * @property {module:model/ReferralConstraints}
     */
    ReferralConstraints,

    /**
     * The ReferralCreatedEffectProps model constructor.
     * @property {module:model/ReferralCreatedEffectProps}
     */
    ReferralCreatedEffectProps,

    /**
     * The ReferralRejectionReason model constructor.
     * @property {module:model/ReferralRejectionReason}
     */
    ReferralRejectionReason,

    /**
     * The RejectCouponEffectProps model constructor.
     * @property {module:model/RejectCouponEffectProps}
     */
    RejectCouponEffectProps,

    /**
     * The RejectReferralEffectProps model constructor.
     * @property {module:model/RejectReferralEffectProps}
     */
    RejectReferralEffectProps,

    /**
     * The RemoveItemCatalogAction model constructor.
     * @property {module:model/RemoveItemCatalogAction}
     */
    RemoveItemCatalogAction,

    /**
     * The RemoveManyItemsCatalogAction model constructor.
     * @property {module:model/RemoveManyItemsCatalogAction}
     */
    RemoveManyItemsCatalogAction,

    /**
     * The ReserveCouponEffectProps model constructor.
     * @property {module:model/ReserveCouponEffectProps}
     */
    ReserveCouponEffectProps,

    /**
     * The ReturnIntegrationRequest model constructor.
     * @property {module:model/ReturnIntegrationRequest}
     */
    ReturnIntegrationRequest,

    /**
     * The ReturnedCartItem model constructor.
     * @property {module:model/ReturnedCartItem}
     */
    ReturnedCartItem,

    /**
     * The Role model constructor.
     * @property {module:model/Role}
     */
    Role,

    /**
     * The RoleAssign model constructor.
     * @property {module:model/RoleAssign}
     */
    RoleAssign,

    /**
     * The RoleMembership model constructor.
     * @property {module:model/RoleMembership}
     */
    RoleMembership,

    /**
     * The RoleV2 model constructor.
     * @property {module:model/RoleV2}
     */
    RoleV2,

    /**
     * The RoleV2ApplicationDetails model constructor.
     * @property {module:model/RoleV2ApplicationDetails}
     */
    RoleV2ApplicationDetails,

    /**
     * The RoleV2PermissionSet model constructor.
     * @property {module:model/RoleV2PermissionSet}
     */
    RoleV2PermissionSet,

    /**
     * The RoleV2Permissions model constructor.
     * @property {module:model/RoleV2Permissions}
     */
    RoleV2Permissions,

    /**
     * The RoleV2PermissionsRoles model constructor.
     * @property {module:model/RoleV2PermissionsRoles}
     */
    RoleV2PermissionsRoles,

    /**
     * The RollbackAddedLoyaltyPointsEffectProps model constructor.
     * @property {module:model/RollbackAddedLoyaltyPointsEffectProps}
     */
    RollbackAddedLoyaltyPointsEffectProps,

    /**
     * The RollbackCouponEffectProps model constructor.
     * @property {module:model/RollbackCouponEffectProps}
     */
    RollbackCouponEffectProps,

    /**
     * The RollbackDeductedLoyaltyPointsEffectProps model constructor.
     * @property {module:model/RollbackDeductedLoyaltyPointsEffectProps}
     */
    RollbackDeductedLoyaltyPointsEffectProps,

    /**
     * The RollbackDiscountEffectProps model constructor.
     * @property {module:model/RollbackDiscountEffectProps}
     */
    RollbackDiscountEffectProps,

    /**
     * The RollbackReferralEffectProps model constructor.
     * @property {module:model/RollbackReferralEffectProps}
     */
    RollbackReferralEffectProps,

    /**
     * The Rule model constructor.
     * @property {module:model/Rule}
     */
    Rule,

    /**
     * The RuleFailureReason model constructor.
     * @property {module:model/RuleFailureReason}
     */
    RuleFailureReason,

    /**
     * The Ruleset model constructor.
     * @property {module:model/Ruleset}
     */
    Ruleset,

    /**
     * The SamlConnection model constructor.
     * @property {module:model/SamlConnection}
     */
    SamlConnection,

    /**
     * The SamlConnectionMetadata model constructor.
     * @property {module:model/SamlConnectionMetadata}
     */
    SamlConnectionMetadata,

    /**
     * The SamlLoginEndpoint model constructor.
     * @property {module:model/SamlLoginEndpoint}
     */
    SamlLoginEndpoint,

    /**
     * The Session model constructor.
     * @property {module:model/Session}
     */
    Session,

    /**
     * The SetDiscountEffectProps model constructor.
     * @property {module:model/SetDiscountEffectProps}
     */
    SetDiscountEffectProps,

    /**
     * The SetDiscountPerAdditionalCostEffectProps model constructor.
     * @property {module:model/SetDiscountPerAdditionalCostEffectProps}
     */
    SetDiscountPerAdditionalCostEffectProps,

    /**
     * The SetDiscountPerAdditionalCostPerItemEffectProps model constructor.
     * @property {module:model/SetDiscountPerAdditionalCostPerItemEffectProps}
     */
    SetDiscountPerAdditionalCostPerItemEffectProps,

    /**
     * The SetDiscountPerItemEffectProps model constructor.
     * @property {module:model/SetDiscountPerItemEffectProps}
     */
    SetDiscountPerItemEffectProps,

    /**
     * The ShowBundleMetadataEffectProps model constructor.
     * @property {module:model/ShowBundleMetadataEffectProps}
     */
    ShowBundleMetadataEffectProps,

    /**
     * The ShowNotificationEffectProps model constructor.
     * @property {module:model/ShowNotificationEffectProps}
     */
    ShowNotificationEffectProps,

    /**
     * The SlotDef model constructor.
     * @property {module:model/SlotDef}
     */
    SlotDef,

    /**
     * The StrikethroughChangedItem model constructor.
     * @property {module:model/StrikethroughChangedItem}
     */
    StrikethroughChangedItem,

    /**
     * The StrikethroughEffect model constructor.
     * @property {module:model/StrikethroughEffect}
     */
    StrikethroughEffect,

    /**
     * The StrikethroughLabelingNotification model constructor.
     * @property {module:model/StrikethroughLabelingNotification}
     */
    StrikethroughLabelingNotification,

    /**
     * The StrikethroughSetDiscountPerItemEffectProps model constructor.
     * @property {module:model/StrikethroughSetDiscountPerItemEffectProps}
     */
    StrikethroughSetDiscountPerItemEffectProps,

    /**
     * The StrikethroughTrigger model constructor.
     * @property {module:model/StrikethroughTrigger}
     */
    StrikethroughTrigger,

    /**
     * The TalangAttribute model constructor.
     * @property {module:model/TalangAttribute}
     */
    TalangAttribute,

    /**
     * The TalangAttributeVisibility model constructor.
     * @property {module:model/TalangAttributeVisibility}
     */
    TalangAttributeVisibility,

    /**
     * The TemplateArgDef model constructor.
     * @property {module:model/TemplateArgDef}
     */
    TemplateArgDef,

    /**
     * The TemplateDef model constructor.
     * @property {module:model/TemplateDef}
     */
    TemplateDef,

    /**
     * The TemplateLimitConfig model constructor.
     * @property {module:model/TemplateLimitConfig}
     */
    TemplateLimitConfig,

    /**
     * The Tier model constructor.
     * @property {module:model/Tier}
     */
    Tier,

    /**
     * The TransferLoyaltyCard model constructor.
     * @property {module:model/TransferLoyaltyCard}
     */
    TransferLoyaltyCard,

    /**
     * The TriggerWebhookEffectProps model constructor.
     * @property {module:model/TriggerWebhookEffectProps}
     */
    TriggerWebhookEffectProps,

    /**
     * The UpdateAccount model constructor.
     * @property {module:model/UpdateAccount}
     */
    UpdateAccount,

    /**
     * The UpdateApplication model constructor.
     * @property {module:model/UpdateApplication}
     */
    UpdateApplication,

    /**
     * The UpdateAttributeEffectProps model constructor.
     * @property {module:model/UpdateAttributeEffectProps}
     */
    UpdateAttributeEffectProps,

    /**
     * The UpdateAudience model constructor.
     * @property {module:model/UpdateAudience}
     */
    UpdateAudience,

    /**
     * The UpdateCampaign model constructor.
     * @property {module:model/UpdateCampaign}
     */
    UpdateCampaign,

    /**
     * The UpdateCampaignCollection model constructor.
     * @property {module:model/UpdateCampaignCollection}
     */
    UpdateCampaignCollection,

    /**
     * The UpdateCampaignGroup model constructor.
     * @property {module:model/UpdateCampaignGroup}
     */
    UpdateCampaignGroup,

    /**
     * The UpdateCampaignTemplate model constructor.
     * @property {module:model/UpdateCampaignTemplate}
     */
    UpdateCampaignTemplate,

    /**
     * The UpdateCatalog model constructor.
     * @property {module:model/UpdateCatalog}
     */
    UpdateCatalog,

    /**
     * The UpdateCollection model constructor.
     * @property {module:model/UpdateCollection}
     */
    UpdateCollection,

    /**
     * The UpdateCoupon model constructor.
     * @property {module:model/UpdateCoupon}
     */
    UpdateCoupon,

    /**
     * The UpdateCouponBatch model constructor.
     * @property {module:model/UpdateCouponBatch}
     */
    UpdateCouponBatch,

    /**
     * The UpdateCustomEffect model constructor.
     * @property {module:model/UpdateCustomEffect}
     */
    UpdateCustomEffect,

    /**
     * The UpdateLoyaltyCard model constructor.
     * @property {module:model/UpdateLoyaltyCard}
     */
    UpdateLoyaltyCard,

    /**
     * The UpdateLoyaltyProgram model constructor.
     * @property {module:model/UpdateLoyaltyProgram}
     */
    UpdateLoyaltyProgram,

    /**
     * The UpdatePicklist model constructor.
     * @property {module:model/UpdatePicklist}
     */
    UpdatePicklist,

    /**
     * The UpdateReferral model constructor.
     * @property {module:model/UpdateReferral}
     */
    UpdateReferral,

    /**
     * The UpdateReferralBatch model constructor.
     * @property {module:model/UpdateReferralBatch}
     */
    UpdateReferralBatch,

    /**
     * The UpdateRole model constructor.
     * @property {module:model/UpdateRole}
     */
    UpdateRole,

    /**
     * The UpdateUser model constructor.
     * @property {module:model/UpdateUser}
     */
    UpdateUser,

    /**
     * The UpdateUserLatestFeedTimestamp model constructor.
     * @property {module:model/UpdateUserLatestFeedTimestamp}
     */
    UpdateUserLatestFeedTimestamp,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserEntity model constructor.
     * @property {module:model/UserEntity}
     */
    UserEntity,

    /**
     * The UserFeedNotifications model constructor.
     * @property {module:model/UserFeedNotifications}
     */
    UserFeedNotifications,

    /**
     * The Webhook model constructor.
     * @property {module:model/Webhook}
     */
    Webhook,

    /**
     * The WebhookActivationLogEntry model constructor.
     * @property {module:model/WebhookActivationLogEntry}
     */
    WebhookActivationLogEntry,

    /**
     * The WebhookLogEntry model constructor.
     * @property {module:model/WebhookLogEntry}
     */
    WebhookLogEntry,

    /**
     * The WillAwardGiveawayEffectProps model constructor.
     * @property {module:model/WillAwardGiveawayEffectProps}
     */
    WillAwardGiveawayEffectProps,

    /**
    * The IntegrationApi service constructor.
    * @property {module:api/IntegrationApi}
    */
    IntegrationApi,

    /**
    * The ManagementApi service constructor.
    * @property {module:api/ManagementApi}
    */
    ManagementApi
};
